### ISSUE TITLE
Iframe issues

### ISSUE THREAD

**Issue by doggie1989** [MachinePublishers/jBrowserDriver#102]

**Comment by hollingsworthd** [comment]
What do you mean by "does not work"? Also, which sites?

**Comment by hollingsworthd** [comment]
Please re-open if you can provide more details. Thanks.

**Comment by doggie1989** [comment]
Hi there,

I have also test the latest version,still can not locate...
code shown also below:
Settings settings = Settings.builder().timezone(Timezone.AMERICA_NEWYORK).ajaxWait(30000)
        .javascript(true).ajaxResourceTimeout(30000).quickRender(false).userAgent(UserAgent.CHROME).logger(null)
        .cache(true).ignoreDialogs(false).build();


     wdForLogin = new JBrowserDriver(settings);
      wdForLogin.get("https://login.aliexpress.com/buyer.htm");

      wdForLogin.switchTo().frame(jdriver.findElement(By.id("alibaba-login-box")));

      Thread.sleep(1000);
      wdForLogin.findElement(By.id("fm-login-id")).sendKeys("910251734@qq.com");
      wdForLogin.findElement(By.id("fm-login-password")).sendKeys("meimei88");
      WebElement verifySlider = jdriver.findElement(By.id("_n1z"));

**Comment by doggie1989** [comment]
@hollingsworthd 

Thanks for fast fix.
When would you push it to maven repo?

**Comment by hollingsworthd** [comment]
It's now released, v0.13.2. Thank you for reporting this! You may need to tweak some of your code to get it to work with their login form. But I believe the main issue was the switchTo for the iframe was not working. That's working now. Note that on the Settings you can set `Settings.builder().headless(false)` which makes it easier to see what's happening.
