### ISSUE TITLE
Return value of WebElement#getText differs from API specification

### ISSUE THREAD

**Issue by BlueIce** [MachinePublishers/jBrowserDriver#103]
The JavaDoc for `WebElement#getText` states:

> Get the visible (i.e. not hidden by CSS) innerText of this element, including sub-elements, without any leading or trailing whitespace.

The [current implementation in `ElementServer`](https://github.com/MachinePublishers/jBrowserDriver/blob/25e5e7b58998c55fc65e1321e3787399325a2b70/src/com/machinepublishers/jbrowserdriver/ElementServer.java#L490-L493) returns the `textContent` attribute of the DOM element. The return value is neither trimmed nor are hidden sub-elements excluded.

**Comment by hollingsworthd** [comment]
Thanks! This is in v0.13.2 which is now released.

**Comment by BlueIce** [comment]
Unfortunately these changes seem to have a side effect when finding elements by link text. As soon as an invisible `a` element is present the `findElementsByLinkText` throws a `ElementNotVisibleException`. This happens because for all `a` elements the `getText` method is called which in turn calls `validate(true)`.

The Problem can be reproduced by adding the following to `Test.java`:
```
<a style="display:none;">invisible anchor</a>
```

**Comment by hollingsworthd** [comment]
Yeah that's a bad regression. I released 0.13.3 just now to fix that. Many thanks!

**Comment by BlueIce** [comment]
That was lightning-fast. :smiley: The problem is now gone, thank you!
