### ISSUE TITLE
Selenium Keys (i.e Keyboard actions) are not working with JBrowser

### ISSUE THREAD

**Issue by anilreddy** [MachinePublishers/jBrowserDriver#104]
Hi,

While executing the following script execution is not getting stopped. Because of Keys.ENTER if you comment that line and use .submit(); it is working as expected.

```java
public class GitHubTest {
	
	WebDriver driver;
	WebDriverWait wait;
	
	@Test
	public void gitHubTest() throws InterruptedException {
		driver = new JBrowserDriver();
		// driver = new FirefoxDriver();
		wait = new WebDriverWait(driver, 60000);
		driver.manage().window().maximize();
		driver.get("https://github.com/");
		if (driver.getTitle().contains("GitHub")) {
			WebElement searchText = driver.findElement(By.name("q"));
			searchText.sendKeys("jBrowserDriver");
			searchText.sendKeys(Keys.ENTER);
			//searchText.submit();
			wait.until(ExpectedConditions.visibilityOfAllElementsLocatedBy(By.xpath("//h3/a[contains(@href,'MachinePublishers')]")));
			driver.findElement(By.xpath("//h3/a[contains(@href,'MachinePublishers')]")).click();
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//h1[text()='jBrowserDriver']")));
		}
		driver.quit();
	}
```
Thanks,
Anil

**Comment by hollingsworthd** [comment]
Thank you for reporting these! I'll look into it.

**Comment by anilreddy** [comment]
@hollingsworthd you are very quick. But will this fix works for all the keyboard actions?

with these: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/Keys.java

**Comment by hollingsworthd** [comment]
What happens is that it waits for http requests to complete after typing enter since those are usually associated with some kind of submission. The wait is brief (150 ms by default) and harmless if there aren't actually http requests being made. However, to do it after every sendKeys call might cause too many delays for people. You can manually call JBrowserDriver.pageWait() which essentially does the same thing.

The same kind of wait is done for form submissions, as you noticed, and left mouse clicks, but nothing else.

**Comment by hollingsworthd** [comment]
I would consider adding it after any call to sendKeys but my intention on this bug report was just to make sendKeys(Keys.ENTER) work the same as sendKeys("\n") or form submit. For now use JBrowserDriver.pageWait() as needed

**Comment by anilreddy** [comment]
@hollingsworthd Thanks for the detailed explanation I have understand what you are saying. My intention here are:

1. JBrowser driver should work for all selenium stuff same like other drivers.
2. Currently we have automation test-suites written to run in different browsers so driver instance would be `WebDriver driver` so for using JBrowserDriver methods we need to change the instance as `JBrowserDriver driver`. Hence we need to change lot of code and we cannot use other browsers.

**Comment by hollingsworthd** [comment]
Yes, but other drivers don't do waiting like this, right?

**Comment by anilreddy** [comment]
@hollingsworthd yes you are right. But changing all testcases are painful job.

**Comment by hollingsworthd** [comment]
I was thinking it over and will probably add the wait to sendKeys calls.
