### ISSUE TITLE
Issuing after submitting login

### ISSUE THREAD

**Issue by Ethan07Scape** [MachinePublishers/jBrowserDriver#107]
The login fields gets entered just fine, but after submitting, it doesn't redirect or anything for this site.
I feel like it has to do with the site using a lot of javascript. Can you please check into?

`

	  JBrowserDriver driver = new JBrowserDriver(Settings.builder()
			   .timezone(Timezone.AMERICA_CHICAGO)
			   .ssl("compatible")
			   .cache(true)
			   .javascript(true)
			   .headless(false)
			   .userAgent(UserAgent.CHROME)
			   .logTrace(true)
			   .build());
    

    driver.get("http://www.runebet.com");
    driver.findElement(By.id("login_username")).sendKeys("-");
	System.out.println("Sent username:");
	driver.findElement(By.id("login_fadeout")).click();
	Thread.sleep(4000);
	driver.findElement(By.id("login_password")).sendKeys("-");
	System.out.println("Sent pass:");
	driver.findElement(By.id("btn_login")).click();
  `

**Comment by hollingsworthd** [comment]
There's some bug in the caching code causing this. Not sure yet but to work around the problem turn caching off: `.cache(false)`

Thanks for reporting this!
