### ISSUE TITLE
The ad-list.txt not found in some setups

### ISSUE THREAD

**Issue by suojian** [MachinePublishers/jBrowserDriver#11]
I run exact example code in my eclipse, and my main thread does not terminate.
I also notice there is a NullPointerException because the ad-list.txt file can't be found, but I'm not sure they're related.

http://grab.by/Msy4

**Comment by hollingsworthd** [comment]
You can add `driver.quit();` on the last line which will let the main thread terminate.

The ad-list.txt is unrelated and appears to be a bug. I'll try to reproduce it but in my environment it works. In the meantime you can set the JRE system property `-Djbd.blockads=false` which will prevent the problematic code from running.

**Comment by hollingsworthd** [comment]
Was able to reproduce both issues. driver.quit() wouldn't work in your setup. Both are fixed in the just-released v0.6.5. Thanks!

**Comment by suojian** [comment]
I have add driver.quit(), but it does not work.

**Comment by hollingsworthd** [comment]
I discovered that too. It should be fixed in v0.6.5 which I released a few minutes ago. Still broken in that version?

**Comment by suojian** [comment]
it works fine now, just tested it , thanks a lot

**Comment by suojian** [comment]
btw, you might need to update the example code in the read.ME, and driver.quit();
