### ISSUE TITLE
Upload file with jQuery File Upload plugin

### ISSUE THREAD

**Issue by BlueIce** [MachinePublishers/jBrowserDriver#110]
Upload of files fails when the site uses the jQuery File Upload plugin.

I think this comes from the fact that jBrowserDriver clicks on the center of the file input element in the `ElementServer#sendKeys` method. But the center of the element is not actually clickable.

(JUnit-)Test case to reproduce this issue:

````java
@Rule
public TemporaryFolder temporaryFolder = new TemporaryFolder();

@Test
public void fileUploadTest() throws Exception {
    JBrowserDriver driver = ...;
    driver.get("http://blueimp.github.io/jQuery-File-Upload/basic.html")
    File file = temporaryFolder.newFile("test.png");
    Files.write(file.toPath(), new byte[] {1, 2, 3});
    driver.findElement(By.id("fileupload")).sendKeys(file.getAbsolutePath());
    TimeUnit.SECONDS.sleep(2);

    MatcherAssert.assertThat(driver.findElement(By.id("files")).getText(),
        CoreMatchers.containsString("test.png"));
}
````

**Comment by hollingsworthd** [comment]
Interesting. Thanks! It will now test using document.elementFromPoint(x,y) and if that doesn't equal *this* then it will start looping to find a point that works.

**Comment by BlueIce** [comment]
Nice, this is working great, thank you.
