### ISSUE TITLE
attribute value for a textfield is returned as null instead of empty

### ISSUE THREAD

**Issue by anilreddy** [MachinePublishers/jBrowserDriver#115]
Hi,

while I am trying to get an attribute value for a textfield if it is empty instead of empty if is returning a null value.

```java
	driver.findElement(By.id("USER")).getAttribute("value");
```
Thanks,
Anil

**Comment by hollingsworthd** [comment]
Selenium's Javadoc's state: "Returns the attribute/property's current value or null if the value is not set." So this is just following the spec.
