### ISSUE TITLE
Block content (CSS/JS/Images etc) from downloading

### ISSUE THREAD

**Issue by fostiropoulos** [MachinePublishers/jBrowserDriver#119]
Similar to how there exists plugins for other drivers that help make everything download and load a lot faster. I think there should be a way to block CSS and specific Javascript from downloading/executing. I couldn't find anything specific in the API. 

I am not sure if the driver even downloads css considering it doesn't need it to render the page. Could someone enlighten me?

**Comment by hollingsworthd** [comment]
Hi, I have plans to eventually support AdBlock-compatible blocklists (EasyList, etc), #33. The driver does download and render CSS, JS, etc. For now, the closest feature is `Settings.builder().blockAds(true)` which simply blocks requests to known ad hostnames. But depending on your needs, that's not really sufficient for something like #33.

**Comment by fostiropoulos** [comment]
Is the rendering etc due to the use of WebKit? Like is it all processed and handled there?

**Comment by hollingsworthd** [comment]
Yes that's right

**Comment by PatrickHuetter** [comment]
I think it would be very useful to have an option within the builder like disableImages(true) and disableStylesheets(true). Is there a workaround to achieve this with jBrowserDriver at this time? (without using a proxy which blocks the request based on some url regex patterns)
