### ISSUE TITLE
Windows OS support

### ISSUE THREAD

**Issue by oahzuw** [MachinePublishers/jBrowserDriver#12]
use jBrowserDriver-v0.6.5.jar
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000072ed4ca0, pid=3728, tid=2592
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [javafx_font.dll+0x4ca0]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\Code\Test\jBro\hs_err_pid3728.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by hollingsworthd** [comment]
Occasionally these crashes happen due to JRE/WebKit bugs. Does it ever work?

FYI, I'll be releasing a newer version soon which will run each instance of JBrowserDriver in a separate process to limit the impact of these types of crashes.

**Comment by oahzuw** [comment]
I have no problem in using the ubuntu14.04, have not succeeded in win7 above

**Comment by hollingsworthd** [comment]
Ok, thanks. I'll take a look. Linux is the primary target for support (Ubuntu, Debian, CentOS, RHEL). But it should work on Windows too.
