### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by fostiropoulos** [MachinePublishers/jBrowserDriver#120]
Chromium is full sized browser, I run some tests on a rather heavy javascript/css website.

ChromiumDriver takes 

5935.861 miliseconds on a cold start
4416.939 miliseconds on a warm start

jBrowserDriver takes
14258.124829  miliseconds on a cold start
   6134.972918 milliseconds on a warm start. 

Now, why would there be such a big discrepancy? 

Another site, less javascript intense than my initial example (Amazon.com,Youtube.com) loads at about the same time on both (Which is not good, considering chromium also has to render, load flash etc) 

Considering Chromium is based on a WebKit fork, are the performance issues somehow related to the implementation of the jBrowserDriver? Usually the slowdowns come from erroneous javascripts, cookies, headers etc that chromium seems to simply ignore.

**Comment by hollingsworthd** [comment]
A large factor is that jBrowserDriver waits for all AJAX page loads. You can effectively disable that by using Settings.builder().ajaxWait(0).

The other issue is that a new instance of JBrowserDriver starts a new JRE process. You can use JBrowserDriver.reset(..) to re-use the already running process.

**Comment by hollingsworthd** [comment]
"considering chromium also has to render" .. jBrowserDriver renders too. You can see it by running in headed mode or using the screenshot API.

**Comment by hollingsworthd** [comment]
I would be curious to hear the numbers if you end up re-running it

**Comment by fostiropoulos** [comment]
Warm request, seems to take about the same time. I think the errors/problems are caused by errors/problems in the headers/javascript etc. 

This is one of the things that keeps popping up for the specific website. 
[2016-05-31T00:47:26.452][Instance 1][Port x] Malformed cookie for cookie named Set-Cookie. Invalid 'expires' attribute:
