### ISSUE TITLE
Issues with SecurityManager

### ISSUE THREAD

**Issue by qqilihq** [MachinePublishers/jBrowserDriver#122]
Hey there,

I've integrated jBrowserDriver in an environment*, where issues are caused through the defined `SecurityManager`: I received some report, that another part of the software where `parallelStream()`s are being used are throwing exceptions.

The exception looks as follows:

```
Thread [main] (Suspended (breakpoint at line 287 in System))	
	System.setSecurityManager(SecurityManager) line: 287	
	Policy.init() line: 30	
	JBrowserDriver.<clinit>() line: 122	
	Unsafe.ensureClassInitialized(Class<?>) line: not available [native
method]	
	UnsafeFieldAccessorFactory.newFieldAccessor(Field, boolean) line: 43	
	ReflectionFactory.newFieldAccessor(Field, boolean) line: 142	
	Field.acquireFieldAccessor(boolean) line: 1088	
	Field.getFieldAccessor(Object) line: 1069	
	Field.get(Object) line: 393	
	jBrowserWebDriverFactory.<clinit>() line: 84	
	NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[])
line: not available [native method]	
	NativeConstructorAccessorImpl.newInstance(Object[]) line: 62	
	DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 45	
	Constructor<T>.newInstance(Object...) line: 423	
	Class<T>.newInstance() line: 442	
	EquinoxRegistryStrategy(RegistryStrategyOSGI).createExecutableExtension(RegistryContributor, String, String) line: 184	
	ExtensionRegistry.createExecutableExtension(RegistryContributor,
String, String) line: 905	
	ConfigurationElement.createExecutableExtension(String) line: 243	
	ConfigurationElementHandle.createExecutableExtension(String) line: 55	
	WebDriverRegistry.loadWebDriverFactories() line: 54	
	WebDriverRegistry.<clinit>() line: 30	
	Activator.start(BundleContext) line: 52	
```

Is there any reason, why jBrowserDriver needs to set its own `SecurityManager` in `Policy.init()`? I can assume that it has to do with the RMI mechanism, but from [my research](http://stackoverflow.com/questions/2298853/java-rmi-with-no-securitymanager) it should only be necessary when code needs to be transferred dynamically.

*) The [Selenium KNIME Nodes](http://seleniumnodes.com).

**Comment by hollingsworthd** [comment]
You're right. I've removed it and made a release v0.14.4 available in Maven Central (it will sync there in a few minutes). Thanks for reporting this!

**Comment by qqilihq** [comment]
Thanks to you for fixing so quickly, really appreciated!
