### ISSUE TITLE
Newbie Question:  IncompatibleClassChangeError

### ISSUE THREAD

**Issue by michael-logan** [MachinePublishers/jBrowserDriver#125]
Hi,

I'm getting the following error trying to replace the HTMLUnitDriver with the your jBrowserDriver.  I've looked online, tried a Maven clean.

The error happens on the instatiation of the object.

`private JBrowserDriver driver = new JBrowserDriver();`

Here is the stack trace.

`java.lang.IncompatibleClassChangeError: Class org.openqa.selenium.remote.DesiredCapabilities does not implement the requested interface org.openqa.selenium.Capabilities
	at org.openqa.selenium.remote.RemoteWebDriver.init(RemoteWebDriver.java:176)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:105)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:264)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.<init>(JBrowserDriver.java:235)
	at AddContact.<init>(AddContact.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)`

Here are my imports

`import java.util.regex.Pattern;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.junit.*;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.WebClient;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;
import java.util.concurrent.TimeUnit;
import com.google.common.base.Function;
import com.machinepublishers.jbrowserdriver.Timezone;
import com.machinepublishers.jbrowserdriver.JBrowserDriver;
import com.machinepublishers.jbrowserdriver.Settings;
`

**Comment by anilreddy** [comment]
@michael-logan can you provide your testcase.

**Comment by michael-logan** [comment]
Yep.  I removed quite a bit of the logic. 

`import java.util.regex.Pattern;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.junit.*;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.WebClient;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;
import java.util.concurrent.TimeUnit;
import com.google.common.base.Function;
import com.machinepublishers.jbrowserdriver.Timezone;
import com.machinepublishers.jbrowserdriver.JBrowserDriver;
import com.machinepublishers.jbrowserdriver.Settings;
import org.openqa.selenium.WebDriver;

public class AddContact {
  //private WebDriver driver;
  //private HtmlUnitDriver driver;
  //private JBrowserDriver driver = new JBrowserDriver(Settings.builder().
  //	      timezone(Timezone.AMERICA_NEWYORK).build());
  private JBrowserDriver driver = new JBrowserDriver();
  //private com.machinepublishers.jbrowserdriver driver = new JBrowserDriver()
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();

  @Before
  public void setUp() throws Exception {
    //driver = new FirefoxDriver();
    //driver = new HtmlUnitDriver(BrowserVersion.FIREFOX_38);
    //driver = new HtmlUnitDriver(BrowserVersion.FIREFOX_38);
    //driver.setJavascriptEnabled(true);
    baseUrl = "https://somesite.com";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    
  }
  
  public void wl(String s) {
	  System.out.println(s);
  }

  @Test
  public void testCONTACTADDANDSEARCH() throws Exception {
    driver.get(baseUrl + "/page1.jsp");
   
    
  }

  @After
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }

  private boolean isElementPresent(By by) {
    try {
      driver.findElement(by);
      return true;
    } catch (NoSuchElementException e) {
      return false;
    }
  }

  private boolean isAlertPresent() {
    try {
      driver.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e) {
      return false;
    }
  }

  private String closeAlertAndGetItsText() {
    try {
      Alert alert = driver.switchTo().alert();
      String alertText = alert.getText();
      if (acceptNextAlert) {
        alert.accept();
      } else {
        alert.dismiss();
      }
      return alertText;
    } finally {
      acceptNextAlert = true;
    }
  }
}
`

**Comment by hollingsworthd** [comment]
I think the dependencies are attempting to use different versions of the same Selenium libraries. Maybe something like this would help: http://stackoverflow.com/a/7176095

... defining this in your POM:

```xml
    <dependencyManagement>
      <dependencies>
        <dependency>
          <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-java</artifactId>
          <version>2.53.0</version>
        <dependency>
      <dependencies>
    <dependencyManagement>
```

**Comment by michael-logan** [comment]
I tried updating the pom.xml dependencies by adding selenium-java to the dependencyManagement section (below) and I'm still getting the same java.lang.IncompatibleClassChangeError error.

pom.xml
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>MyCompany</groupId>
  <artifactId>MyProject</artifactId>
  <version>1.0.0</version>
  
  <pluginRepositories>
	    <pluginRepository>
	      <id>onejar-maven-plugin.googlecode.com</id>
	      <url>http://onejar-maven-plugin.googlecode.com/svn/mavenrepo</url>
	    </pluginRepository>
    </pluginRepositories>
    
    <build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.6</version>
				<executions>
					<execution>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.seleniumhq.selenium</groupId>
				<artifactId>selenium-java</artifactId>
				<version>2.53.0</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-htmlunit-driver</artifactId>
			<version>2.52.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium.server</groupId>
			<artifactId>selenium-server-coreless</artifactId>
			<version>1.0.3</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium.core</groupId>
			<artifactId>selenium-core</artifactId>
			<version>1.0.1</version>
		</dependency>
		<dependency>
  			<groupId>com.machinepublishers</groupId>
  			<artifactId>jbrowserdriver</artifactId>
  			<version>[0.14.0, 2.0)</version>
		</dependency>
	</dependencies>
</project>`

**Comment by hollingsworthd** [comment]
Also try changing selenium-htmlunit-driver to 2.53.0

**Comment by hollingsworthd** [comment]
Also with selenium-core and selenium-server-coreless Selenium 1.x libraries end up getting included.

**Comment by michael-logan** [comment]
Thanks for the help...this seems to work for me.

`<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.seleniumhq.selenium</groupId>
				<artifactId>selenium-java</artifactId>
				<version>2.53.0</version>
			</dependency>
			<dependency>
				<groupId>org.seleniumhq.selenium</groupId>
				<artifactId>selenium-htmlunit-driver</artifactId>
				<version>2.53.0</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
  			<groupId>com.machinepublishers</groupId>
  			<artifactId>jbrowserdriver</artifactId>
  			<version>[0.14.0, 2.0)</version>
		</dependency>
	</dependencies>`

**Comment by michael-logan** [comment]
Thanks @hollingsworthd moving selenium-htmlunit-driver and selenium-java into dependencyManagement while removing core and coreless seemed to work.
