### ISSUE TITLE
Error loading javascript

### ISSUE THREAD

**Issue by master2501** [MachinePublishers/jBrowserDriver#126]
Webpage is loaded but some javascript is having problems loading...

[2016-06-07T17:37:58.609][Instance 1][Port 64064] {"console_log":["Registering Graphs.Handler"]}
[2016-06-07T17:37:58.609][Instance 1][Port 64064] {"console_log":["Handler: Registered Graphs handler"]}
[2016-06-07T17:37:58.610][Instance 1][Port 64064] {"console_log":["Registering SystemChannels.Handler"]}
[2016-06-07T17:37:58.610][Instance 1][Port 64064] {"console_log":["Handler: Registered SystemChannels handler"]}
**[2016-06-07T17:37:58.632][Instance 1][Port 64064] {"window_onerror":"TypeError: setting a property that has only a getter","filename":"URL_REMOVED/assets/mwdcomm.js?1464775345","lineno":2387}**

Portion of the Javascript file:

.....

(function () {
    "use strict";

    //@todo : Do this to turn off the console.logging. Preferably by using a configuration variable.

    /**
     * Small console handler to handle logs silently
     */
    var ConsoleHandler = {
            storage: [],
            types: [
                'error',
                'log',
                'info',
                'warn'
            ]
        };

    /**
     * Console output store
     * @param type
     * @param arguments
     */
    ConsoleHandler.storeLog = function(type, args) {
        ConsoleHandler.storage.push({
            type: type,
            arguments: args
        });
    };

    /**
     * Outputs stored console
     */
    ConsoleHandler.consoleOutput = function() {

        ConsoleHandler.storage.forEach(function (log) {
            //the only method which does not get overwritten
            console.debug.apply(console, ["[" + log.type.toUpperCase() + "]"].concat(log.arguments));
        });
    };

    /**
     * Ducktype for console methods.
     * @param type
     * @returns {Function}
     */
    function getConsoleHandlerType(type) {
        return function () {
            return ConsoleHandler.storeLog(type, arguments);
        }
    }

    /**
     * console.drain
     * Drains all the stored log
     */
    window.console.drain = function () {
        ConsoleHandler.consoleOutput();
    };

    /**
     * Mask console methods
     * Comment to leave the console untouched
     */

ERROR HERE
--- 
    **ConsoleHandler.types.forEach(function (type) {
        window.console[type] = getConsoleHandlerType(type);
    });**
----
    //--- Set DOM loaded listener
    window.addEventListener('DOMContentLoaded', App.launch, false);

}());

I think this script is using the browser's localstorage. 
Is this supported by jbrowserDriver? or it can be included?

Best regards,

Files:
[mwdcomm.txt](https://github.com/MachinePublishers/jBrowserDriver/files/303411/mwdcomm.txt)

**Comment by askvortsov** [comment]
Local Storage works OK, but modifying built-in ``window.console``- not.

**Comment by hollingsworthd** [comment]
I agree with @askvortsov -- the error message "TypeError: setting a property that has only a getter" usually indicates you're modifying a built-in variable in a way the browser does not permit. There can be ways around this sometimes but generally that's the cause.

**Comment by hollingsworthd** [comment]
You might also try running this with `.logJavascript` left disabled because it too modifies console and might be conflicting with this script.
