### ISSUE TITLE
can i use jBrowserDriver download http file ?

### ISSUE THREAD

**Issue by oahzuw** [MachinePublishers/jBrowserDriver#13]
can i use jBrowserDriver download http file ?
like http://xxx.com/t.txt 

if can ,how to do??

**Comment by hollingsworthd** [comment]
Yes, you can call getPageSource() which works for most filetypes.

    JBrowserDriver driver = new JBrowserDriver(Settings.builder().timezone(Timezone.AMERICA_NEWYORK).build());
    driver.get("https://github.com/robots.txt");
    System.out.println(driver.getPageSource());
    driver.quit();

If it's a file that prompts the user to download it, then it's saved to ./download_cache. See `Settings.Builder.downloadDir(File)`

**Comment by oahzuw** [comment]
I try this,but can't run it ,throw one Exception ( Exception in thread "main" java.lang.UnsupportedClassVersionError: com/machinepublishers/jbrowserdriver/JBrowserDriver : Unsupported major.minor version 52.0 )
In the above test win7 and centos 7
Use the above code, use  jBrowserDriver  version 0.6.6

**Comment by hollingsworthd** [comment]
There's an open issue about problems with running this on Windows. Linux should work. Make sure to use Java 8; that's what the error is referring to.

**Comment by oahzuw** [comment]
Oh .. sorry, linux jdk 1.7 version of the above, I try, thank you very much
