### ISSUE TITLE
Problem trying to install jBrowserDriver on GWT project

### ISSUE THREAD

**Issue by SrCobranza** [MachinePublishers/jBrowserDriver#135]
Hello guys.

I've just added the dist jars to my project Build Path, pasted the first example but i'm getting this error when trying to compile my GWT project:

>       [ERROR] Line 74: No source code is available for type com.machinepublishers.jbrowserdriver.JBrowserDriver; did you forget to inherit a required module?
>       [ERROR] Line 74: No source code is available for type com.machinepublishers.jbrowserdriver.Settings; did you forget to inherit a required module?
>       [ERROR] Line 75: No source code is available for type com.machinepublishers.jbrowserdriver.Timezone; did you forget to inherit a required module?

I want to know if I've missed some step or this is happening because this modules can't be used with GWT.

**Comment by hollingsworthd** [comment]
Hi, I haven't tried this in GWT, but are you using this in the GWT client? If so, I don't think that would work, as GWT compiles Java code in the client to Javascript/HTML and the Java code in JBrowserDriver is simply too complex to be compiled like that. On the server side it should work.
