### ISSUE TITLE
Taking full page screenshot (given a viewport width)?

### ISSUE THREAD

**Issue by oschrenk** [MachinePublishers/jBrowserDriver#138]
Is there a way of taking full page screenshots and not just of the viewport?

**Comment by oschrenk** [comment]
For now this workaround is good enough for me 

```
// driver.get ...
val bodyHeight = driver.findElement(By.tagName("body")).getSize.height
driver.manage().window().setSize(new Dimension(viewportWidth, bodyHeight))
```

I feel this screenshot behaviour should be default or at leas have a better API around it. I see at #113 that you actually already consider adding that. Closing.

**Comment by Zero3** [comment]
@oschrenk I'm having the same issue as you. Unfortunately, your work around is not working for me :(. I still get just the upper part of the page. Am I missing something?

````
JBrowserDriver driver = new JBrowserDriver();
driver.get(URL);
int bodyHeight = driver.findElementByTagName("body").getSize().height;
driver.manage().window().setSize(new Dimension(SCREENSHOT_WIDTH, bodyHeight));
byte[] screenshot = driver.getScreenshotAs(OutputType.BYTES);
Files.write(Paths.get("screenshot.png"), screenshot);
````

I checked the value of the `bodyHeight` int, and it is much larger than the height of the resulting .png file which appears to be locked to 1000x600 pixels no matter what values I pass to `.setSize()`.

**Comment by Zero3** [comment]
@oschrenk Never mind, I figured it out! The size apparently cannot exceed the screen size specified in the settings for the driver. For example:

````
Settings settings = Settings.builder().screen(new Dimension(SCREENSHOT_WIDTH, LARGE_CONSTANT)).build();
JBrowserDriver driver = new JBrowserDriver(settings);
````

I don't know of a good way to pick a value for `LARGE_CONSTANT` though. A value of `Integer.MAX_VALUE` causes an internal crash at `java.nio.ByteBuffer.allocate(ByteBuffer.java:334)`, likely because of a too large memory allocation.

**Comment by sidneydemoraes** [comment]
I don't know if it is of any help, but I'm using [AShot ](https://github.com/yandex-qatools/ashot) for that. It just performs all necessary scrolls and automagically merges all screenshots into a single image. The end result is perfect.
