### ISSUE TITLE
Support specifying localstorage location

### ISSUE THREAD

**Issue by Elusive138** [MachinePublishers/jBrowserDriver#140]
There doesn't seem to be a way to configure the localstorage backing store at the moment, or I missed it.

Looks like it should be enough to expose [`userDataDirectoryProperty`](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/web/WebEngine.html#userDataDirectoryProperty) as a Setting?

**Comment by askvortsov** [comment]
I'd vote for at least starting with clean localStorage by setting userDataDirectory to process temporary subdir. Cookies aren't saved anyway.

**Comment by Elusive138** [comment]
Actually, my intention in asking for this is so I can maintain the same storage across sessions! Currently using phantomjs/ghostdriver for that.

**Comment by Elusive138** [comment]
Thanks!
