### ISSUE TITLE
Ubuntu issue with java version

### ISSUE THREAD

**Issue by dramer** [MachinePublishers/jBrowserDriver#142]
This step does not work for me.

Ubuntu 14.04: sudo add-apt-repository ppa:webupd8team/java && sudo apt-get install oracle-java8-installer libgtk2.0 libxtst6 libxslt1.1 fonts-freefont-ttf libasound2

oracle-java8-installer can't be found. I was reading that java8 was not available for Ubuntu 14.04

thanks for the help

**Comment by hollingsworthd** [comment]
I probably should have written:

sudo add-apt-repository ppa:webupd8team/java **&& sudo apt-get update** && sudo apt-get install oracle-java8-installer libgtk2.0 libxtst6 libxslt1.1 fonts-freefont-ttf libasound2

Java 8 isn't available from official Ubuntu repositories for Ubuntu 14.04, so the webupd8 PPA is what most people have used as an alternative.

**Comment by dramer** [comment]
hey thanks for the quick response. I'm not sure I understand the commands! Do I run them all in one line or are they separate like the following:

sudo add-apt-repository ppa:webupd8team/java

then run
sudo adt-get update

then run

sudo adt-get install oracle-java8-installer libgtk2.0 libxts6 libxslt1.1 fonts-freefont-ttf libasound2


thank you so much for the help
Dave

**Comment by hollingsworthd** [comment]
Either way works. The && just forces them to be run sequentially but it's effectively the same as running them separately one after the other.

**Comment by dramer** [comment]
all is working. one last question, do I need to run this under java 1.8? so my eclipse needs 1.8 and not 1.7

**Comment by hollingsworthd** [comment]
If Java 7 is your system default, Eclipse itself runs on that that which should be ok, but you'll need Java 8 also installed and configured as an execution environment within Eclipse and specified on the jBrowserDriver build path.

**Comment by dramer** [comment]
all is working now with java-8-oracle
