### ISSUE TITLE
Opening links in a new window when headless mode is enabled

### ISSUE THREAD

**Issue by rcmul** [MachinePublishers/jBrowserDriver#145]
I can open links in a new browser window when the JBrowserDriver is visible using:

Actions action= new Actions(driver);
action.contextClick(link).sendKeys(Keys.ARROW_DOWN).sendKeys(Keys.ARROW_DOWN).sendKeys(Keys.RETURN).build().perform();

...but this action seems to be disabled in headless mode. Is there any way to open new windows while the browser is not visible?

**Comment by hollingsworthd** [comment]
I had done some work to make shift+click work to open links in new windows. It's an incomplete feature when it comes to divs and fancy javascript links, but for a basic anchor I think it will work.

**Comment by hollingsworthd** [comment]
Try:

````java
  driver.getKeyboard().pressKey(Keys.SHIFT);
  someElement.click();
  driver.getKeyboard().releaseKey(Keys.SHIFT);
````

**Comment by rcmul** [comment]
That works perfectly. Thanks!
