### ISSUE TITLE
Asian language characters not rendered

### ISSUE THREAD

**Issue by riu-ixl** [MachinePublishers/jBrowserDriver#150]
I'm trying to take screenshots of my website with this library. It seems like the driver isn't able to render characters from Asian languages correctly - they just look like boxes. I've tried Chinese, Japanese, Korean, and Thai.
Any idea of how to get around this? Thanks!

Here's the screenshot that I get:
![capture](https://cloud.githubusercontent.com/assets/13577975/16642140/93fa66b4-43bc-11e6-8334-bcf05bec53e7.PNG)

**Comment by hollingsworthd** [comment]
From the Settings.Builder try setting .quickRender(false) to enable webfonts. However quickRender is enabled by default because of Java 8 memory leaks. So you could instead leave quickRender default to true and try to install system fonts: https://wiki.openjdk.java.net/display/OpenJFX/Font+Setup
