### ISSUE TITLE
[Feature Request] seleniumQuery support

### ISSUE THREAD

**Issue by dhruvbhatia** [MachinePublishers/jBrowserDriver#151]
It would be awesome if jBD supported one of WebDriver's popular third-party selector engines, such as [seleniumQuery](https://github.com/seleniumQuery/seleniumQuery).

I played around with `seleniumQuery` and while it can take a custom driver, it specifically wants a `WebDriver` instance rather than a `JBrowserDriver` instance.

I wonder if it would make sense to either a) add support for a popular selector engine; or alternatively b) have a method that casts a `JBrowserDriver` instance to a `WebDriver` lookalike one so that it can be used with these third-party libraries.

**Comment by hollingsworthd** [comment]
It's a WebDriver. I think it might work.

**Comment by hollingsworthd** [comment]
Closing issue because the class JBrowserDriver extends RemoteWebDriver which implements WebDriver. Please report back if there are problems with this framework.

**Comment by dhruvbhatia** [comment]
Thanks. I can pass a jBrowserDriver instance to seleniumQuery's `$.driver().use(driver)` function, however any subsequent calls to their API results in hanging.

For example, the [second example in their Readme explains how to use an existing WebDriver instance](https://github.com/seleniumQuery/seleniumQuery#no-special-configuration-needed---use-it-in-your-project-right-now), but this does not work with jBD (it gets stuck when `$(...selector...)` is called).
Replacing jBD with Firefox or Chrome works as expected.

Happy to report this issue to the seleniumQuery project if it's better suited there?

**Comment by hollingsworthd** [comment]
It works now per latest commit.
