### ISSUE TITLE
JBrowserDriver as a thread not process

### ISSUE THREAD

**Issue by michael-logan** [MachinePublishers/jBrowserDriver#154]
I am using JMeter with a Java Request Sampler.  Inside my sampler I am using the JBrowserDriver driver.  When I run my test through JMeter the Java processes are equivalent to the amount of users I specified on the Thread Group.   Is there a way to prevent an external process from being started?  I'd like to use the JBrowserDriver as a thread within the JMeter process.  Thanks for any help.

**Comment by hollingsworthd** [comment]
This would require some modifications to work within a single process. Please follow issue #123 for status on that work.

**Comment by michael-logan** [comment]
Thanks for the update @hollingsworthd
