### ISSUE TITLE
Non-breaking space (&nbsp) in element text can't be trimmed off.

### ISSUE THREAD

**Issue by rcmul** [MachinePublishers/jBrowserDriver#155]
For an element: &lt;div&gt;&amp;nbsp;&lt;div&gt;

WebElement element = driver.findElement(By.tagName("div"));
String text= element.getText(); // value is " "
text = text.trim(); // value is still " "

**Comment by qqilihq** [comment]
This is nothing jBrowserDriver-specific. Non-breaking spaces are never removed by Java's `trim()`.
