### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by jjlauer** [MachinePublishers/jBrowserDriver#156]
I'm interested in contributing and I was curious how the project is currently tested.  There isn't a `src/test/java` directory, so is there something else used to verify jBrowser works as expected?

**Comment by hollingsworthd** [comment]
Hi, please see https://github.com/MachinePublishers/jBrowserDriver/tree/master/src/com/machinepublishers/jbrowserdriver/diagnostics ... I decided to just keep it in the main source tree to make sure build scripts never strip out the tests and they're always available to run if you're configuring a new system etc. Glad you're interested in contributing!
