### ISSUE TITLE
scrollIntoView for click, sendKeys issue

### ISSUE THREAD

**Issue by jjlauer** [MachinePublishers/jBrowserDriver#157]
For sites w/ a static navigation bar -- the click and sendKeys events and the `scrollIntoView` call before sending the event causes issues on some sites.  My best guess is that the navigation bar overlays the element.  Chrome doesn't seem to do this in its implementation.  jBrowser also appears to jump around (scrolling) when you fill in a form.  Do you think adding that before those (and maybe other) actions is correct?

**Comment by jjlauer** [comment]
As an update it looks like another bug was actually the root cause.  Although it still seems like calling `scrollIntoView` causes some pages to jump around while other selenium drivers (e.g. chrome) don't have the same behavior.

**Comment by hollingsworthd** [comment]
Firefox driver does this, although I think it's configurable. A Settings option could be added to let users disable this. Also if the element is already fully visible then scrolling ideally should not happen.

**Comment by askvortsov** [comment]
Firefox scrolls an element into view only if that element is out of view.

**Comment by JeffBolle** [comment]
I'm also encountering a similar issue.  I have static elements that get scrolled off the page, and then when the click or sendKeys actions are called for those elements, there is seemingly no effect.

I had believed that the Selenium WebDriver spec implied that if an element was present, but not visible in the viewport due to the need to scroll, that the WebDriver would automatically scroll to it and put it in view.  

Either auto-scrolling, or throwing an ElementNotVisibleException so that I can do the scrolling myself would be preferable to the current situation.

**Comment by hollingsworthd** [comment]
It's good to know about this. Thanks for the feedback.

**Comment by askvortsov** [comment]
I may not have checked JBrowser behavior for some time, but earlier it was just scrolling into view everything everytime it is clicked or going to receive keys.

**Comment by JeffBolle** [comment]
@askvortsov I haven't run a comprehensive series of tests, but I do have a couple cases where I have run into this behavior.  Unfortunately they are on internal URLs that I can't provide, but I have a static search box on the left and a long table in the middle of the page. When it loads in JBrowser it seems to scroll towards the middle of the page. When I go to put text in the search box and click search, nothing happens.  

I have solved this in the short term by setting the screen to be 10000 pixels tall, which means it never needs scrolling.  However, this feels like an ugly solution, and the screenshots I capture during errors are much uglier this way with all of the extra unnecessary whitespace.

**Comment by askvortsov** [comment]
Would it require a lot of efforts to cut all the stuff around one of your cases so that is won't expose anything internal?

**Comment by JeffBolle** [comment]
Sorry it took me a while today to get back to this. It looks like it has already been addressed.  I'm not using JBrowserdriver directly from Github, I'm including it during releases from Maven, so I'll check this out when the next release hits.  Thank you for addressing this so quickly.
