### ISSUE TITLE
Head-ful?

### ISSUE THREAD

**Issue by kerrykimbrough** [MachinePublishers/jBrowserDriver#159]
Nice job! JBrowserDriver has been very helpful for my UI test project. Beats GhostDriver+PhantomJS hands down!

I use JBrowserDriver primarily for its headless capability. But what does it mean to operate in "head-ful" mode? What exactly do you see and how? What dependencies are required?

**Comment by hollingsworthd** [comment]
Dependencies are no different than running in headless mode--except you need a desktop OS essentially. You see a browser window and your mouse cursor automatically moving, etc.
