### ISSUE TITLE
Can't run on OpenJdk8 JVM

### ISSUE THREAD

**Issue by kerrykimbrough** [MachinePublishers/jBrowserDriver#161]
For CI, we use Jenkins running in the AWS cloud, on instances running Linux and the OpenJDK8 JVM. Unfortunately, that means my tests using headless JBrowserDriver fails because certain Oracle-specific classes are undefined. For example:

```
java.lang.NoClassDefFoundError: com/sun/webkit/network/CookieManager
```

Not sure how to fix this. What to do?

**Comment by hollingsworthd** [comment]
That's provided by Java FX. See https://github.com/machinepublishers/jbrowserdriver#prerequisites

**Comment by hollingsworthd** [comment]
It's part of the JRE but Linux distro's package it separately. Ideally you can just run `sudo apt-get install openjfx`
