### ISSUE TITLE
Not handling post data when clicking an element that triggers javascript to post on click

### ISSUE THREAD

**Issue by adcoelum** [MachinePublishers/jBrowserDriver#162]
Hi,

I am using JBrowserDriver to crawl pages on this site: www.mcgrath.com.au.  However, I have run into an edge case, which seems not to behave as a browser normally would.  On this page (as an example): https://www.mcgrath.com.au/offices/126-ascot, the 4 orange buttons in the middle when clicked trigger javascript that sets certain variables in a form on the page and then causes a submit of that form, therefore triggering an http POST.

In JBrowserDriver, I get the page and click on the button.  This seems to register the click and correctly trigger a POST method (shown by running through Browsermob.)  However, it appears that it does not seem to be sending the POST data to the page.

Any help in understanding what is happening here and if it is possible to fix would be great.

Thanks,
  Jeremy

**Comment by askvortsov** [comment]
If it doesn't send anything in POST, then you should try upgrading to 0.14.12. There was an issue with connections wrapping.

**Comment by adcoelum** [comment]
Perfect!  Updating from 0.14.11 to 0.14.12 worked.  Thanks for your help.
