### ISSUE TITLE
Script timeout is used for different purposes.

### ISSUE THREAD

**Issue by askvortsov** [MachinePublishers/jBrowserDriver#164]
``com.machinepublishers.jbrowserdriver.TimeoutsServer#getScriptTimeoutMS`` seems to be used in a lot places _except_ the one of its intention: ``com.machinepublishers.jbrowserdriver.ElementServer#executeAsyncScript`` will cycle indefinitely.
``org.openqa.selenium.WebDriver.Timeouts#setScriptTimeout`` tells us, that the value is specifically for ``org.openqa.selenium.JavascriptExecutor#executeAsyncScript`` and nothing else.

I suggest to drop timeout argument whereever ``getScriptTimeoutMS`` is used now (guess it works well anyway with default ``0``) and implement constraint in ``executeAsyncScript``.

**Comment by hollingsworthd** [comment]
Yes, I consider deviations from the Selenium spec to be a bug. Agreed that timeout of zero everywhere else should be fine.

**Comment by askvortsov** [comment]
It seems timeout in ``AlertServer`` is used to wait for internal driver stuff. I've added a separate setting for it.
Is it possible to merge with PR?
