### ISSUE TITLE
javaOptions not being used

### ISSUE THREAD

**Issue by michael-logan** [MachinePublishers/jBrowserDriver#167]
I'm trying to limit the maximum heap size of the JVM created by JBrowserDriver.  Here is the instantiation of the object.

driver = new JBrowserDriver(Settings.builder().javaOptions("-Xmx200m").build());

However I never see the -Xmx200m option appear on the command line and I don't see it through the Windows Process/Task Manager.

Here is the maven dependency for JBrowserDriver:

       <dependency>
  			<groupId>com.machinepublishers</groupId>
  			<artifactId>jbrowserdriver</artifactId>
  			<version>0.14.4</version>
		</dependency>

Thanks.  Mike

**Comment by hollingsworthd** [comment]
try `.javaOptions("-XX:+PrintCommandLineFlags", "-Xmx200m")`

Outputs: "... -XX:MaxHeapSize=209715200 ..."
