### ISSUE TITLE
A bit of info in README.md comparing it to ui4j would be nice

### ISSUE THREAD

**Issue by davegrow** [MachinePublishers/jBrowserDriver#17]
I'm familiar with [Ui4j|https://github.com/ui4j/ui4j] and it looks like this is very similar. Would you be able to add a small note to the README.md comparing the implementation of jBrowserDriver vs. ui4j?

**Comment by hollingsworthd** [comment]
Sure, I'll have to look at it some more. Interesting project. Briefly, each browser instance is run in a separate OS process which isolates the impact of very occasional browser crashes. This is common with browsers when you're automating them for hundreds of thousands of requests.

Also, jBrowserDriver has some better support for ajax.

There's more extensive support to control all the user agent details, not just the user agent string. E.g. request headers can be customized and re-ordered, the navigator JS object can be customized, timzeone set, etc. Right now there are defaults for Tor and Chrome. Others could be set up by users using the APIs.

Also couldn't tell the extent of their features here, but jBrowserDriver can issue keyboard events and clicks. You can also control the screen size.

ui4j does have nice support for attaching to JS events. We don't exactly have that although you can execute custom JS to accomplish a similar thing.

Overall, we follow the Selenium WebDriver API (aside from configuration APIs) some there's some benefit in not being coupled too closely to a unique API and being able to switch over to other drivers.

**Comment by davegrow** [comment]
> Briefly, I think unlike ui4j, each jBrowserDriver instance is run in a separate OS process which isolates the impact of very occasional browser crashes. 

Cool!

> Also, jBrowserDriver has some better support for ajax.

Cool!

> Overall, we follow the Selenium WebDriver API (aside from configuration APIs) some there's some benefit in not being coupled too closely to a unique API and being able to switch over to other drivers.

Totally agree, happy to see this type of implementation as a WebDriver. I've had mixed success with HtmlUnitDriver.

I've had some issues scraping a particular site using ui4j (but got much further than with HtmlUnit). I'll try out jBrowserDriver and submit any issues I find. Thanks.

**Comment by hollingsworthd** [comment]
Hopefully this info suffices. I don't think I'll have enough time to properly research ui4j to write anything official. Maybe one day I'll write up an article comparing various popular drivers to jBrowserDriver.

**Comment by franz-see** [comment]
UI4j uses javafx webview underneath. How about jBrowserDriver? Does it use anything underneath or did it implement its own browser?

**Comment by hollingsworthd** [comment]
It uses JavaFX WebView. Note the networking backend utilizes Apache HttpComponents by setting a custom handler for HTTP/S protocols.
