### ISSUE TITLE
the program pause when I close remote windows

### ISSUE THREAD

**Issue by donaldlee2008** [MachinePublishers/jBrowserDriver#172]
jBrowserDriver, 
headless(false);

the program run well in local PC.
when I run the program in a remote windows 7  server(from local %windir%\system32\mstsc.exe 3389 port)
it runs well in the remote  server, but when I close the  remote windows in my pc
,we know the  remote server is still running. but the program pause. 
when I login the remote windows again. the program continue.
headless(true) does not have such problem.

**Comment by hollingsworthd** [comment]
This seems to be the the intended/configured behavior of Windows Server. Also headed mode in this project is intended for debugging not production/server use.
