### ISSUE TITLE
Can I use this to interact with website in a WebView?

### ISSUE THREAD

**Issue by brcolow** [MachinePublishers/jBrowserDriver#173]
Hello,

Is it possible to use jBrowserDriver to interact with a (headed or headless) JavaFX WebView itself? I am currently developing a JavaFX desktop application that uses various WebViews. Can jBrowserDriver be used to interact with the loaded website of a WebView?

Thanks for clarification,

**Comment by hollingsworthd** [comment]
That's not possible today. Theoretically it's possible. The JBrowserDriver constructor would need to accept a WebView instance and not spawn child processes (the WebView right now is controlled via RMI to protect against JRE crashes taking down the parent JRE). This would be essentially the work of #123. It's not actually that hard to get something rudimentary like this working, which I've done, but hammering out all the details to make everything work perfectly would take some effort. Please follow #123 for future updates on this.

**Comment by brcolow** [comment]
Thanks a lot.
