### ISSUE TITLE
Lots of jumping to AppThread

### ISSUE THREAD

**Issue by askvortsov** [MachinePublishers/jBrowserDriver#176]
While I were investigating problem with slow input, I've noticed, that `com.machinepublishers.jbrowserdriver.Robot#keysTypeHelper` schedules a job to be run in JavaFX thread for every key press. I think a cycle is that thread would be better but:
I've also noticed that there are a lot (≈80) of usages of different `execs`. Almost in every Selenium API method.
I wonder, why was such design used? Why not a queue filled with commands as in Selenium's RemoteWebDriver and processed by a job in the JavaFX thread?

**Comment by hollingsworthd** [comment]
The delay on key press is intentional. It should be very short for each key press. Some ajax sites put listeners on text boxes and typing at robot speed can cause errors.

Regarding the usage of execs, there's no way around that with JavaFX. Most anything that affects the UI must be put on the Application even thread and only one thread will run at a time. Sleeping or waiting will cause a hang.

**Comment by hollingsworthd** [comment]
If the delay between key presses is longer than 100 ms there's probably a bug and please report that.

**Comment by hollingsworthd** [comment]
One more thing, after a call to sendKeys, there's a wait for any ajax requests to finish. If you have a very high value for `Settings.builder().ajaxWait(long)` then things will be slow.

**Comment by askvortsov** [comment]
For me it seems to run at symbol-per-frame speed. Wikipedia says most advanced 'touch writers' can achieve 100wpm speed. Times 5 symbols per word it's like 8-9 symbols per second. So input is already faster then a human can produce. :)
Anyway, what about the idea of processing commands by the worker already in the JavaFX thread?

**Comment by hollingsworthd** [comment]
Unless the keystrokes are in separate events then there's no update in the browser between keystrokes. What exactly is the problem you're experiencing?

**Comment by askvortsov** [comment]
Well, I can only recall one scenario when I actually want an update after each keystore and before I type whole word/sentence. Search for autocomplete. But while doing such a search, I actually analyze the response. In terms of WebDriver, that means, that I get back to 'driving' context, wait for AJAX (one way or another), fetch autocomplete options and decide on the next move. And that implies I ask to sendKeys with one-chat argument.
Do you know of any usage scenario, when a user would type key-by-key, wait for browser to do some job in between, but not use any result of such a job before he types the last key?
Regarding the problem: currently I have a focus-based race condition. Timings in the code are good for slow users (humans) and fast users (async robots), but not for not-so-fast v-synced robots.

**Comment by hollingsworthd** [comment]
Yes, I've seen typing too fast be a problem on form validation. Also it's sort of a goal that the robot interact with a website like a human would.

I would be ok with adding a setting to configure the delay (or disable it) between keystrokes. In AppThread.java you could comment out line 175 `pause();` and if that fixes things for you then a setting like this would make things work.

As far as putting each key stroke into the same event... that breaks things. I know especially on "\n" and probably other cases. I don't think I'd consider such a change.

**Comment by askvortsov** [comment]
We can't put all keystrokes in one event. But we can avoid framesync delay. If we input all keys at once, browser will fire several events.

**Comment by hollingsworthd** [comment]
Let me know if commenting out line 175 in AppThread.java fixes things for you. I explained the issue with putting all keys in same event above. I can review a PR if you'd like.

**Comment by askvortsov** [comment]
For me there were no race condition actually but rather `WebElement#getText()` returning `null` for empty fields. And my calling code was assuming it is not equal to empty strings. Obviously, changing `AppThread` did nothing. :)
Though I'd like to try not-v-synced input one day.

**Comment by hollingsworthd** [comment]
I think the behavior of `WebElement@getText()` is different now. Looks like it will return empty string instead of null in every case.
