### ISSUE TITLE
Setting config options in code rather than through JVM args

### ISSUE THREAD

**Issue by ruggy** [MachinePublishers/jBrowserDriver#19]
It would be very handy to be able to set config options in code rather than as project properties - making things more flexible and easier to customize based on application logic. 

Example: jbd.ajaxWait - depending on the site, or the resources needed for the site, different timeouts might be useful. Or jbd.browsergui - 

In addition, having all the options be enums in the API would help to quickly lookup which options are available, and the available setters would make it obvious which ones are mutable. As written in a README, there is always room to wonder if the list is complete.

**Comment by hollingsworthd** [comment]
Good points. Agreed.

**Comment by vrosu** [comment]
I also add a need for this enhancement. If the lib it's started from a webserver side, then it's quite strange to pass specific arguments from the JVM side.
