### ISSUE TITLE
Question - Use selenium 3.0.0-betaX 

### ISSUE THREAD

**Issue by edesantis** [MachinePublishers/jBrowserDriver#196]
Hi team, 

Can I use jBrowserDriver with any of selenium 3.0.0-betaX versions? 

Thanks

**Comment by hollingsworthd** [comment]
It hasn't been tested with those versions. There may be some compilation/runtime errors regarding missing classes.

Generally it will be small fixes if any required to make JBrowserDriver compatible with 3.x. As I understand Selenium 3.x removes Selenium 1.x classes. JBrowserDriver doesn't really make use of Selenium 1.x classes.

**Comment by hennr** [comment]
jbrowserdriver works fine for me with selenium-java version 3.0.1

Can this ticket be closed?

**Comment by edesantis** [comment]
Hi @hennr ,

Sure, i post the steps of how to use the driver with 3.x version here.

#207 

Regards
E.
