### ISSUE TITLE
Question - enhance Can we run jBrowserDriver on android 

### ISSUE THREAD

**Issue by tuyuri2201** [MachinePublishers/jBrowserDriver#202]
Can we bring JBrowserDriver to  Android ? I love a headless browser on android too much but i have never found out something like that

**Comment by hollingsworthd** [comment]
It's a little far off from being Android compatible I think. If it were stripped down to only run one instance concurrently and reduce the dependencies, with a lot of work it could probably work. I'd recommend checking out https://github.com/selendroid/selendroid and all the drivers here: http://www.seleniumhq.org/download/

**Comment by hollingsworthd** [comment]
Oh, but I'm not sure if those are headless...
