### ISSUE TITLE
Most efficient/fastest way to get page views

### ISSUE THREAD

**Issue by EliteMail** [MachinePublishers/jBrowserDriver#209]
We are architecting a web app and want to stress test it by hitting it with a bunch of page views from JBrowserDriver. What would be the fastest/most efficient way to do that? Our current method is an infinite loop like so:

while(true){
      driver.get (URL)
      driver.quit();
}

We've tried using .refresh() instead, but our software did not register those as unique hits on the server. Is there a better way? .get() each time seems like a bit of overkill.

**Comment by hollingsworthd** [comment]
I would do:

````java
JBrowserDriver driver = JBrowserDriver(Settings.builder().userDataDirectory(DATA_DIR).build());
while(true){
  driver.get (URL)
  driver.get("about:blank");
  driver.manage().deleteAllCookies();
  org.apache.commons.io.FileUtils.cleanDirectory(DATA_DIR);
}
````
Caching is disabled by default so getting about:blank, clearing cookies, and clearing local storage should be enough to effectively reset the state.

**Comment by hollingsworthd** [comment]
Note that underlying tcp may be kept alive. JBrowserDriver.reset(..) would probably close them (in addition to clearing cookies and local storage) but there's a memory leak in that API. There's an open issue where someone suggested how to fix it. Pull requests welcome.

**Comment by EliteMail** [comment]
OK, but do we still need to call .get() on each iteration no matter what?
Is there no faster way? For example, would doing driver.navigate().to(Same
URL) be faster? Or is that the same as .get() under the surface?

**Comment by hollingsworthd** [comment]
`Get` needs to be called and there's no faster alternative. If you want `get` itself to be faster you can disable javascript although with most websites accurately performance testing them would require JS to be enabled, as the JS would often be making http requests back to the server under test.

**Comment by EliteMail** [comment]
Ok. We will try disabling Javascript. To confirm, driver.navigate.to(url)
is the same performance as driver.get(url)?

**Comment by hollingsworthd** [comment]
Confirmed. `Navigate.to` is implemented by calling `driver.get`. Per Selenium API they're by design the same contract.
