### ISSUE TITLE
Is there any  no javaFX , graphical  barnch?

### ISSUE THREAD

**Issue by onlyforzhuce** [MachinePublishers/jBrowserDriver#211]
now we use phantomjs to crawler pages, and we find jbrowserDriver . But jBrowserDriver can not run in  a no graphics library linux server.
we do not want to use a graphical interface, just want to have a pure Java version of the browser alternative phantomjs.

**Comment by hollingsworthd** [comment]
JavaFX is part of the JRE and available on every operating system.

**Comment by hollingsworthd** [comment]
Also to clarify there is no desktop or monitor needed. It runs headlessly. On Ubuntu/Debian server run `apt-get install openjdk-8-jre openjfx` to install the JRE.
