### ISSUE TITLE
Problem with sendKeys

### ISSUE THREAD

**Issue by ZaziroZ** [MachinePublishers/jBrowserDriver#226]
Hello there,

Let's assume there is some input WebElement inputField;

Command `inputField.sendKeys(Keys.CONTROL + "a", Keys.DELETE)` should select all and then delete everything in the input field

Instead, jBrowserDriver types "a" into the field.

Regards

**Comment by FranAguiar** [comment]
Just use inputField.clear();

**Comment by ZaziroZ** [comment]
But this works fine in normal drivers.

Okay, in this case inputField.clear(); can do. But doesn't it mean that other Keys commands do not work with jBrowserDriver as well?

**Comment by hollingsworthd** [comment]
Haven't test this but maybe `inputField.sendKeys(Keys.chord(Keys.CONTROL + "a") + Keys.DELETE)` or `inputField.sendKeys(Keys.chord(Keys.CONTROL + "a")); inputField.sendKeys(Keys.DELETE)`

If other drivers handle `sendKeys(Keys.CONTROL + "a", Keys.DELETE)` this one should too.
