### ISSUE TITLE
does not support WebDriverWait 

### ISSUE THREAD

**Issue by linlihuiyang** [MachinePublishers/jBrowserDriver#237]
when i use other webdriver , i used WebDriverWait usually, but jbrowserDriver does not support,
advice to add selenium-support in pom

**Comment by hollingsworthd** [comment]
If it's just a matter of adding the dependency, then users should do that on their own. The goal is to have as few dependencies as possible to make compilation and basic use cases work. Is there something more that makes this lib incompatible with WebDriverWait (code changes needed)?
