### ISSUE TITLE
How to embed jBrowserDriver on Swing jFrame

### ISSUE THREAD

**Issue by animexxx** [MachinePublishers/jBrowserDriver#24]
I want to embed browser on jFrame or other components of Java Swing, it helps view web more easy for user and easy for control mutil-browser. Can this driver can do it? Thanks

**Comment by hollingsworthd** [comment]
It doesn't support this and would require some modifications. You would prefer this project over using Java's [WebView](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/web/WebView.html) directly? This project wraps WebView.

**Comment by hollingsworthd** [comment]
You'd add a JFXPanel to your JFrame. Then add WebView to the JFXPanel... https://docs.oracle.com/javase/8/javafx/interoperability-tutorial/swing-fx-interoperability.htm

**Comment by animexxx** [comment]
Thank you, let me try
