### ISSUE TITLE
How to keep facebook login after reset or create new jbrowserdriver

### ISSUE THREAD

**Issue by nddong26** [MachinePublishers/jBrowserDriver#241]
Hi all,
I'm working on login to facebook, but when my application need to restart, jbrowserdriver will be recreated.
Before restart app: Facebook was login
After restart: I make a request to http://www.facebook.com, but it show login page (i've login again)

I try to cache cookie, and set after request to facebook.com, but it still show login page.
Anybody help???
Thanks!

**Comment by hollingsworthd** [comment]
Would need some more info to determine if this is a bug that needs to be fixed.
