### ISSUE TITLE
com.machinepublishers.jbrowserdriver.Dimension can't be used - not public

### ISSUE THREAD

**Issue by ruggy** [MachinePublishers/jBrowserDriver#26]
In package com.machinepublishers.jbrowserdriver, the class Dimension isn't public. For now I don't know how to use it to pass an instance to the Settings.Builder.screen() method, and as a result I don't know how to set window size when showing the gui.

**Comment by hollingsworthd** [comment]
Thanks. Fix is committed. I'll be making a release within a couple of days.

**Comment by ruggy** [comment]
Excellent! Thank you very much.
