### ISSUE TITLE
Selenium 3 says "I'm sorry but your browser is not supported"

### ISSUE THREAD

**Issue by mvysny** [MachinePublishers/jBrowserDriver#260]
Thank you for the amazing driver, finally a driver with which Selenium simply works :-)

I tried to upgrade to Selenium 3 and unfortunately there is something really broken. The browser says, quoting:

> I'm sorry, but your browser is not supported
The version (38.0) of the browser you are using is outdated and not supported.
You should consider upgrading to a more up-to-date browser.

A screenshot of the issue:
![clickbuttonshouldchangethelabel my vaadin app test myfirstit](https://cloud.githubusercontent.com/assets/254091/23659049/84555cb8-034d-11e7-831e-c1064ad209f9.png)

You can easily reproduce this issue by checking out this project:
https://github.com/mvysny/testbench4-starterkit
*tag* jbrowser-error

And simply run 
```
mvn clean verify
```

**Comment by hollingsworthd** [comment]
Thanks!

That might not be related to the Selenium 3 upgrade and could be just that the default user agent at this point needs updating. However it can be specified as such:

````java
new JBrowserDriver(Settings.builder()
  .requestHeaders(RequestHeaders.CHROME)
  .userAgent(new UserAgent(
    UserAgent.Family.WEBKIT,
    "Google Inc.",
    "Win32",
    "Windows NT 6.1",
    "5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2869.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2869.0 Safari/537.36")))
````

**Comment by mvysny** [comment]
Awesome, that helped, thank you!

**Comment by hennr** [comment]
@mvysny Would you mind closing this issue then?

**Comment by mvysny** [comment]
Sure, apologies. @hennr please do you know where this screen comes from? Is it perhaps rendered by JBrowserDriver, Selenium, or perhaps by the TestBench?

**Comment by hennr** [comment]
My guess would be the URL you got via the driver, your vaadin app [most probably](https://vaadin.com/forum#!/thread/3261779).
