### ISSUE TITLE
The original structure of  the xml file is not present while getting the page source.

### ISSUE THREAD

**Issue by saikatmohajan** [MachinePublishers/jBrowserDriver#268]
**CODE:**
JBrowserDriver driver = new JBrowserDriver(Settings.builder().
                timezone(Timezone.AMERICA_NEWYORK).build());
driver.get("http://www.jcpenney.com/sitemap.xml");
System.out.println(driver.getStatusCode());
System.out.println(driver.getPageSource());
driver.quit();

The original structure of  the xml file is not present while getting the page source.

**Comment by hollingsworthd** [comment]
Thanks for pointing this out. Fixed now.

**Comment by saikatmohajan** [comment]
Thank you @hollingsworthd for quick response. It works now.
