### ISSUE TITLE
Try to login to facebook but no cookies activated

### ISSUE THREAD

**Issue by dlaske** [MachinePublishers/jBrowserDriver#278]
Hello,
i try to login to facebook with the jbrowser but i got an issue that 
no cookies activated. WIth phantomjs i could successfully logged in. This is my source to initialize the jbrowser:
`private static JBrowserDriver getJBrowserDriver() {`
`		Builder builder = Settings.builder()`
`				.requestHeaders(RequestHeaders.CHROME)`
`				.userAgent(UserAgent.CHROME).cache(true)`
`				.cacheDir(new File("/tmp"));`
`		JBrowserDriver driver = new JBrowserDriver(builder.timezone(`
`				Timezone.EUROPE_BERLIN).build());`

`		return driver;`
`	}`

I hope you could give me a hint to fix it.

Thanks in advance

**Comment by dlaske** [comment]
Do you want an example? @hollingsworthd

**Comment by hollingsworthd** [comment]
I think this is enough to go on. Thank you for submitting this issue!

**Comment by dlaske** [comment]
Thank you that you help me to use this library. ;-) @hollingsworthd

**Comment by dlaske** [comment]
@hollingsworthd i really need this fix. Could you give me a hint to fix it ?

**Comment by hollingsworthd** [comment]
Try settings both of these to true:

http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/Settings.Builder.html#logTrace-boolean-
http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/Settings.Builder.html#logWire-boolean-

That will show all the http request info including Set-Cookie headers etc.

**Comment by hollingsworthd** [comment]
I tried this and it's working here, so the logs may offer some insight.

**Comment by hollingsworthd** [comment]
Also try setting Settings.builder().headless(false) and log in manually to rule out that there's some problem in the custom automation instead of the cookie handling.

**Comment by dlaske** [comment]
@hollingsworthd Now i tried headless = false and it works. But i want it headless. Do you need the log file ?

**Comment by hollingsworthd** [comment]
There are some differences in headed vs headless but not that many. It may be worth using the screenshot API to take screenshots after every browser action (button clicks etc). http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/JBrowserDriver.html#getScreenshotAs-org.openqa.selenium.OutputType-

**Comment by hollingsworthd** [comment]
I extended my previous comment significantly. If reading via email notification please see thread at website for edits.

**Comment by dlaske** [comment]
@hollingsworthd I send you an email with the log and a screenshot...
