### ISSUE TITLE
After updating to 0.8.1 - Could not find or load main class JBrowserDriverServer

### ISSUE THREAD

**Issue by ruggy** [MachinePublishers/jBrowserDriver#28]
My code uses JBrowserDriver with a maven dependency to it. When I saw there was a new release last week, I updated dependency from 0.7.3 to 0.8.1 and when I tried to run it, I got the error: 

"Error: Could not find or load main class com.machinepublishers.jbrowserdriver.JBrowserDriverServer". 

Reverting to version 0.7.3 by changing nothing but the version number in my pom.xml fixes the issue (but loses the enchancements and fixes found in the new version). 

Is it possible that I should be changing my usage in order to properly use the new version?

**Comment by ruggy** [comment]
Great!

**Comment by doanchu** [comment]
Work Ok for Windows but for Mac, the same error still occurs.
