### ISSUE TITLE
Cookies don't work but exists

### ISSUE THREAD

**Issue by andreaskas** [MachinePublishers/jBrowserDriver#308]
Hello,

I am trying to login headless to pages such as facebook, twitter and in sites with login forms in general. and i get from the page that cookies are required, despite the cookies are enabled and that i can view them in debug using manage().getCookies()

For example at facebook login, although the credentials are correct, when i am trying to login i get the following page.

![image](https://user-images.githubusercontent.com/3345028/32431022-73486030-c2da-11e7-83f0-d422978c1658.png)

if i manally login, it logins and fb appears me a notification that cookies in my browser are not enabled.

I am using latest Ubuntu LTS (16.04.3) and openjdk version "1.8.0_131" with all the required packages in README installed and tested with versions 0.17.10 & 0.17.11.
Is there a known issue or anything i can do to trace down a possible error?

**Comment by hollingsworthd** [comment]
Possibly fixed by `#351 from zipleen/cookie_fix2`

Thanks for the info!
