### ISSUE TITLE
canvas rendering issue

### ISSUE THREAD

**Issue by leemgk** [MachinePublishers/jBrowserDriver#342]
Hi. I'm trying to render some charts in canvas, but the result is not the same as other browsers'.

**Comment by leemgk** [comment]
Sorry to bother you, but could you help me for solving this? @hollingsworthd

**Comment by fangjiaxiaobai** [comment]
why close?

**Comment by leemgk** [comment]
> why close? are you sloved?

需要清空作者默认添加的js代码，在配置驱动的时候添加.headscript('')

**Comment by xiaoyi001yeye** [comment]
> > why close? are you sloved?
> 
> 需要清空作者默认添加的js代码，在配置驱动的时候添加.headscript('')

如何操作，能详细说说吗？
