### ISSUE TITLE
cookiemanager noclassdeffounderror

### ISSUE THREAD

**Issue by Devopssquadtechire** [MachinePublishers/jBrowserDriver#344]
java.lang.NoClassDefFoundError: com.sun.webkit.network.CookieManager
      at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:80)
Caused by: java.lang.ClassNotFoundException: com.sun.webkit.network.CookieManager

i am getting the above error for redhat linux 7.4 (RHEL) we are using IBM J9VM
oracle jdk8u91-b14

is the JVM/JDK missing something? How to get rid of this error?

**Comment by hollingsworthd** [comment]
Making a distribution to include javafx would mean bundling our own JRE which to me doesn't seem like what an library like this should be doing.

Yeah in the last couple of years linux distros tended to make JavaFX a separate package from the JDK necessitating a step to install e.g. openjfx (apt-get install openjfx on ubuntu).

**Comment by elect86** [comment]
Any news?
I have the same issue, I tried to import javafx manually but it didn't fix it

```
plugins {
    ..
    id("org.openjfx.javafxplugin") version "0.0.10"
}
..
javafx {
    version = "17.0.1"
    modules = modules + "javafx.controls"
}
```
