### ISSUE TITLE
Can't create JBrowserDriver - AccessControlExceptions all over the place

### ISSUE THREAD

**Issue by outofrange** [MachinePublishers/jBrowserDriver#38]
Hi!

I just wanted to try out your WebDriver implementation, but when trying to `new JBrowserDriver`, I get exceptions because of your configured security policy (`System.getSecurityManager()` returned null before instantiating a new JBrowserDriver).

If the word SecurityManager alone does ring a bell to you, I would be happy to read your ideas :)

But if that's somewhat unexpected, I can try to provide a small example reproducing the problem - and actual stacktraces (would have done that already, but I've very little time right now)

Oh, and I'm supposed to say that detro / ghostdriver sent me :)

**Comment by hollingsworthd** [comment]
Hi. It seems you have set your own security manager somewhere. In that case, jBrowserDriver will not set its own. So you'll need to modify your security policy to allow RMI connections. Let me know how it goes.

**Comment by outofrange** [comment]
I've never had to deal with security policies before, so I don't really know - but if there was a Security Manager in place, `System.getSecurityManager()` shouldn't return null, should it?
`Policy.init()` is being executed and the SecurityManager created by jBrowserDriver can be set without throwing an exception.

Anyway, I'll create an example in the following week.
I've tried using jBrowserDriver in tests for a Spring Boot application, my best guess is that it has something to do with Spring.

**Comment by hollingsworthd** [comment]
I set up a sample spring boot app and can reproduce this. I'll look into it.

**Comment by outofrange** [comment]
Wow, thanks, that was fast! :+1:

Out of curiosity: do you have any idea why Spring Boot doesn't lile AllPermission-SecurityManagers?

**Comment by hollingsworthd** [comment]
I never totally figured it out. For whatever reason the policy file was having no effect. Typically the policy file should be specified as a command line option during startup, so I figure specifying it at runtime is unexpected and not compatible with Spring Boot.
