### ISSUE TITLE
Enable getLocation and getSize for WebElement

### ISSUE THREAD

**Issue by fabiana001** [MachinePublishers/jBrowserDriver#42]
I need t get the location and position of the WebElements that I'm extracting. Is it possible to enable it? If you know how we can discuss and I will implement it by myself. 

thanks

**Comment by hollingsworthd** [comment]
Happy to accept pull requests. In this case it was a bug regarding serialization of the objects over RMI which I just fixed. It will be released in v0.9.3 by tomorrow. Thanks!
