### ISSUE TITLE
StackOverflowError in setSize

### ISSUE THREAD

**Issue by uwemaurer** [MachinePublishers/jBrowserDriver#44]
Caused by: java.lang.StackOverflowError
[Port 10000] 	at com.machinepublishers.jbrowserdriver.WindowServer.setSize(WindowServer.java:146)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.WindowServer.setSize(WindowServer.java:146)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.WindowServer.setSize(WindowServer.java:146)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.WindowServer.setSize(WindowServer.java:146)

I think this line 146 should be  

setSize(dimension.toSelenium());

**Comment by hollingsworthd** [comment]
Thanks! Will be included in next release, 0.10.1
