### ISSUE TITLE
Simple example does not work

### ISSUE THREAD

**Issue by Jazzepi** [MachinePublishers/jBrowserDriver#46]
Using the example from the Readme does not work. This is my code.

```
public class Main {
    public static void main(String[] args) {
        JBrowserDriver driver = new JBrowserDriver(Settings.builder().
                timezone(Timezone.AMERICA_NEWYORK).build());
        driver.get("http://example.com");
        System.out.println(driver.getStatusCode());
        System.out.println(driver.getPageSource());
        driver.quit();
    }
}

```

This is the exception that I get. I had a local firewall on and thought that might be the issue, but I had allowed the connection through, and then I also disabled the firewall and it did not help.

```
[Port 10000] Exception in thread "main" java.lang.NullPointerException
[Port 10000] 	at com.machinepublishers.jbrowserdriver.LogsServer.exception(LogsServer.java:110)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:97)
```

```
This is my build.gradle file.

group 'test'
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.machinepublishers:jbrowserdriver:0.10.1'
    testCompile group: 'junit', name: 'junit', version: '4.11'
}
```

**Comment by hollingsworthd** [comment]
There should be a better error message but I believe it's because something else is currently running on port 10000 (another instance of JBrowserDriver?). Try JBrowserDriver driver = new JBrowserDriver(Settings.builder().ports(1010).
                timezone(Timezone.AMERICA_NEWYORK).build());

**Comment by hollingsworthd** [comment]
The firewall might also be a problem, as this uses remote method invocation on loopback ports.  Maybe the firewall causes a prior instance to hang and then it tied up the port.

**Comment by Jazzepi** [comment]
It was the port. Turns on uTorrent was squatting on port 10000.

Thanks for the help!

I'm actually a little surprised. It looks like there's some code in there that iterates over ports looking for an open one.

**Comment by hollingsworthd** [comment]
That code you saw only keeps track of which ports jBrowserDriver itself is using. It could be smarter about this.

Also FYI since you have a firewall, I just discovered it's actually using other ports too because of Java's default behavior (RMI registry happens on the specified port but subsequent communication is using any available port). I'll fix some of this up for the next release.

**Comment by mikagika** [comment]
I just ran into this same exact problem. For my use case, I will really need to have a way for it to pick an open port itself as I may have an indeterminate number of these running on the same machine (in separate JVMs).

**Comment by mikagika** [comment]
Possible code for finding free port:
https://gist.github.com/vorburger/3429822

I changed my code to be:
    JBrowserDriver driver = new JBrowserDriver(Settings.builder().
        timezone(Timezone.AMERICA_NEWYORK).
        ports(findFreePort()).
        build());

It worked in my simple test case, but whether that's sufficient in all cases I can't say.

**Comment by qqilihq** [comment]
FYI: There's `org.openqa.selenium.net.PortProber.findFreePort()` in Selenium which will get you a free port.

**Comment by mikagika** [comment]
Even better!

**Comment by hollingsworthd** [comment]
Ok, I'll add something like this. @mikagika I think it would still need some kind of max on number on concurrent processes, otherwise it's too easy to crash your machine. Maybe I'll set that max to Runtime.getRuntime().availableProcessors() and you could override it to Integer.MAX_VALUE if needed.
