### ISSUE TITLE
ExpectedConditions.elementToBeClickable times out

### ISSUE THREAD

**Issue by 5hawnknight** [MachinePublishers/jBrowserDriver#53]
When I use ExpectedConditions.elementToBeClickable, the driver will timeout. For example --
WebElement button = new WebDriverWait(driver,30).until(ExpectedConditions.elementToBeClickable(driver.findElement(By.cssSelector("locator"))));

But the following will work as expected
WebDriverWait(driver,30).until(ExpectedConditions.visibilityOf(driver.findElement(By.cssSelector("locator"))));

Error message: 
org.openqa.selenium.TimeoutException: Timed out after 30 seconds waiting for element to be clickable: com.machinepublishers.jbrowserdriver.Element@72035809
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'Shawns-MacBook-Pro.local', ip: '172.16.42.181', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_65'
Driver info: com.machinepublishers.jbrowserdriver.JBrowserDriver
Session ID: 1:10000

	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)
       ........

**Comment by hollingsworthd** [comment]
Can you provide a test case? I can't reproduce this.

**Comment by 5hawnknight** [comment]
I am using Java 8
Selenium version: 2.48.2
jbrowserdriver:0.10.1

here is the code I am using -- 

 JBrowserDriver driver = new JBrowserDriver(Settings.builder().
                timezone(Timezone.AMERICA_CHICAGO).build());
        driver.navigate().to(request.getLocationUri().toString());

        WebDriverWait webDriverWait = new WebDriverWait(driver,30);
        WebElement emailTextBox = webDriverWait.until(ExpectedConditions.elementToBeClickable,(driver.findElementByName("emailaddr")));
        emailTextBox.sendKeys("xxxxxx@gmail.com");

html -- 
<input type="email" name="emailaddr" autocapitalize="off" autocorrect="off" autocomplete="email" required="" data-qa-hook="signin.email.textbox">
