### ISSUE TITLE
Multiple calls to get(String) not thread safe

### ISSUE THREAD

**Issue by kenyee** [MachinePublishers/jBrowserDriver#54]
The docs could use an example of this?
I.e., can you create one JBrowserDriver and have multiple threads call .get() on it to speed up a web scraping job?  When I do this, the JVM crashes in jfxrt.dll :-(

**Comment by hollingsworthd** [comment]
Yes, to do that, create multiple instance of JBrowserDriver then use multiple threads.

**Comment by hollingsworthd** [comment]
Number of concurrent instances is limited by number of configured RMI ports, `new JBrowserDriver(Settings.builder.ports(..).build())`

I'll leave this open to fix multiple calls to get() issue...

**Comment by kenyee** [comment]
I looked at the code for .ports() and it seems to default to 8 ports:
* Defaults to <code>10000,10001,10002,10003,10004,10005,10006,10007</code>
.portsMax also defaults to:
* Defaults to <code>10000,8</code>

I'm just creating a JBrowserDriver and then each thread is calling .get() where I tried setting maxthreads to 5 and it still crashes out the JVM.
Test harness is here if you want to try it:
https://github.com/kenyee/EmailScraper
run it with "<domainname> -maxthreads 5" for parameters and it'll crash eventually.

**Comment by hollingsworthd** [comment]
Each thread needs its own instance.

**Comment by kenyee** [comment]
Thanks...wasn't obvious from the docs.... :-)

**Comment by kenyee** [comment]
Actually, another quick question if you don't mind...
You can stuff it the instance into a threadlocal like so:
`````
    private ThreadLocal<JBrowserDriver> browserDriver = new ThreadLocal<JBrowserDriver>() {
        @Override
        protected JBrowserDriver initialValue() {
            try {
                JBrowserDriver instance = new JBrowserDriver(Settings.builder()
                        .timezone(Timezone.AMERICA_NEWYORK)
                        .build());
                return instance;
            } catch (Throwable e) {
                throw new RuntimeException(e);
            }
        }
    };
`````
but how do you clean it up if you're using a threadpool?
When it gets garbage collected, will browserDriver.quit() automatically get called?

**Comment by hollingsworthd** [comment]
No, quit won't be automatically called. Maybe I could add it to finalize...

**Comment by hollingsworthd** [comment]
I don't know of any way to get the finalizer to run automatically. There are references held by RMI and JavaFX indefinitely. JBrowserDriver.quit() must be called.
