### ISSUE TITLE
Host name does not match the certificate subject provided by the peer

### ISSUE THREAD

**Issue by shackman0** [MachinePublishers/jBrowserDriver#57]
I am using the latest JBrowserDriver from here: https://github.com/MachinePublishers/jBrowserDriver. 

I want to eliminate the "Host name 'foobar' does not match the certificate subject provided by the peer" exception. Here's what I do with org.apache.http.HttpClient:

   	TrustStrategy trustStrategy = new TrustSelfSignedStrategy();
	SSLContext sslContext = SSLContexts.custom().loadTrustMaterial(trustStrategy).build();
	HostnameVerifier hostnameVerifier = NoopHostnameVerifier.INSTANCE;

	StatusLine statusLine;
	try (CloseableHttpClient httpclient = HttpClients.custom().setSSLContext(sslContext).setSSLHostnameVerifier(hostnameVerifier).build()) {
		HttpGet httpGet = new HttpGet(deviceStatusURI);
		...
	}

Is there a way to do something similar with JBrowserDriver?

**Comment by hollingsworthd** [comment]
You can disable SSL validation with Settings.builder().ssl("trustanything")

**Comment by shackman0** [comment]
here is my settings object:

		settings = Settings
				.builder()
				.timezone(Timezone.EUROPE_AMSTERDAM)
				.headless(true)
				.ignoreDialogs(true)
				.ssl("trustanything")
				.userAgent(UserAgent.CHROME)
				.ajaxWait(5000)
				.requestHeaders(RequestHeaders.CHROME)
				.build();

in use when i get the exception.

**Comment by hollingsworthd** [comment]
Oh, that's a bug then. I'll look into it. Thanks for reporting this.

**Comment by BlueIce** [comment]
I had the same problem before and added a setting for it: https://github.com/BlueIce/jBrowserDriver/tree/hostname-verification.
If you want i can make a pull request.

**Comment by shackman0** [comment]
when do you think you'll be releasing this?

**Comment by hollingsworthd** [comment]
@shackman0 probably within a week
