### ISSUE TITLE
getPageSource() doesn't return the finalized DOM

### ISSUE THREAD

**Issue by shackman0** [MachinePublishers/jBrowserDriver#58]
I browse to a web page that looks like this:

![image](https://cloud.githubusercontent.com/assets/11311687/13665529/43d92a1a-e6ad-11e5-853f-c6da6653fb7e.png)

Here is the page source (right click: view page source):

	
	
	
	
	<HTML>
		<HEAD>
			<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
			<meta http-equiv="Content-Style-Type" content="text/css">
			<meta http-equiv="Content-Script-Type" content="text/javascript">
			<meta name="viewport" content="width=device-width, minimum-scale=0.1, maximum-scale=5.0,target-densitydpi=device-dpi, user-scalable=yes"/>
		</HEAD>
		<script language="JavaScript">
			var idxlang = "dut";
			var opt_msg1_exist = "_mode_on";
			if( opt_msg1_exist == "_mode_on")
			{
			var opt_msg1_name = "Português";
			}
		</script>
		<frameset border=0 frameborder=NO framespacing=0>
			<frame name=wlmframe  src="/startwlm/Start_Wlm.htm">
		</frameset>
	</HTML>	

and here's the start of the DOM as shown in Chrome Developer Tools:

![image](https://cloud.githubusercontent.com/assets/11311687/13665689/fc3098b4-e6ad-11e5-88c4-b54441051fbe.png)

as you can see, the final DOM is frame within frame within frame.

here are the settings i'm using with jBrowserDriver:

	settings = Settings
		.builder()
		.ajaxResourceTimeout(5000)
		.ajaxWait(5000)
		.blockAds(true)
		.headless(true)
		.ignoreDialogs(true)
		.requestHeaders(RequestHeaders.CHROME)
		.ssl("trustanything")
		.timezone(Timezone.EUROPE_AMSTERDAM)
		.userAgent(UserAgent.CHROME)
		.build();

In this case, and in this case only, when I call jBrowserDriver#getPageSource(), i get the View Page Source version of the page rather than the completed, rendered, full DOM version of the page as shown by Developer Tools.

The only unique thing that I can identify about this particular web page is that it's a series of very deeply nested framesets.

i need the completed DOM. how do i get it in this case?

**Comment by hollingsworthd** [comment]
The iframe sources are not included in the page source. Use JBrowserDriver.switchTo().frame(..) to activate the iframe you need then call getPageSource to get that specific iframe's source.

As far as getting the page source, including all the iframes, I need to check what other Selenium drivers are doing. I think they do it the same way, omitting iframes. Not sure if adding the iframes would cause regressions or unexpected behavior. I'll leave this open as an enhancement but am not sure I'll change the functionality.

**Comment by shackman0** [comment]
i wrote a document assembler that "deep dives" into all the frames and attaches them to the appropriate place in the top-level document. The problem is that the iframe's getPageSource() returns the original source code, not the post-process rendered version. so i never dive any deeper than 1 level and even then the source is pre-processed source.

	/**
	 * 1. browse to the URL using the current driver
	 * 2. capture the results. dives "deep" into iframes and includes their sources as well.
	 * @param url
	 * @param pageSource
	 * @return response code
	 * @throws TransformerException
	 * @throws IOException
	 * @throws ParserConfigurationException
	 * @throws SAXException
	 */
	public int browse(String url, Carrier<String> pageSource) throws IOException, TransformerException, SAXException, ParserConfigurationException {
		JBrowserDriver localDriver = getDriver();
		localDriver.get(url);
		Document dom = recurseIntoFrames(localDriver);
		int statusCode = localDriver.getStatusCode();
		pageSource.setPayload(dom.toString());

		return statusCode;
	}

	/**
	 * the "top" of the document assembler process.
	 * dives "deep" into iframes and includes their sources as well.
	 * @param browserDriver
	 * @return a Document that contains the entirety of the rendered page
	 * @throws IOException
	 * @throws TransformerException
	 * @throws SAXException
	 * @throws ParserConfigurationException
	 */
	Document recurseIntoFrames(JBrowserDriver browserDriver) throws IOException, TransformerException, SAXException, ParserConfigurationException {
		TargetLocator switchTo = browserDriver.switchTo();
		switchTo.defaultContent();    // start at the top
		String pageSource = browserDriver.getPageSource();
		Document document = Jsoup.parse(pageSource);
		Elements frameElements = document.getElementsByTag("frame");
		for (int i = 0; i < frameElements.size(); i++) {
			Element frameElement = frameElements.get(i);
			switchTo.frame(i);
			recurseIntoFramesHelper(switchTo, browserDriver, frameElement);
			switchTo.parentFrame();
		}

		return document;
	}

	/**
	 * appends frame documents that appear within the parent element
	 * @param switchTo
	 * @param browserDriver
	 * @param parent
	 * @throws IOException
	 * @throws TransformerException
	 * @throws SAXException
	 * @throws ParserConfigurationException
	 */
	void recurseIntoFramesHelper(TargetLocator switchTo, JBrowserDriver browserDriver, Element parent) throws IOException, TransformerException, SAXException, ParserConfigurationException {
		String pageSource = browserDriver.getPageSource();
		Document document = Jsoup.parse(pageSource);
		parent.appendChild(document);
		Elements frameElements = document.getElementsByTag("frame");
		for (int i = 0; i < frameElements.size(); i++) {
			Element frameElement = frameElements.get(i);
			switchTo.frame(i);
			recurseIntoFramesHelper(switchTo, browserDriver, frameElement);
			switchTo.parentFrame();
		}
	}

here's an abbreviated version of the final page source:

	<html>
	 <head> 
	  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> 
	  <meta http-equiv="Content-Style-Type" content="text/css"> 
	  <meta http-equiv="Content-Script-Type" content="text/javascript"> 
	  <meta name="viewport" content="width=device-width, minimum-scale=0.1, maximum-scale=5.0,target-densitydpi=device-dpi, user-scalable=yes"> 
	  <script language="JavaScript">
	var idxlang = "1";
	if(idxlang == "49") idxlang = "deu";			//Dutch
	else if(idxlang == "1")  idxlang = "eng";		//English
	else if(idxlang == "34") idxlang = "esp";		//Spanish
	else if(idxlang == "33") idxlang = "fra";		//French
	else if(idxlang == "39") idxlang = "ita";		//Italian
	else if(idxlang == "81") idxlang = "jpn";		//Japanese
	else if(idxlang == "31") idxlang = "dut";		//Nederlands
	else if(idxlang == "7")  idxlang = "rus";		//Portugues
	else idxlang = "eng";

	var opt_msg1_exist = "_mode_on";
	if( opt_msg1_exist == "_mode_on")
	{
	var opt_msg1_name = "Português";
	}
	</script>
	 </head> 
	 <frameset border="0" frameborder="NO" framespacing="0"> 
	  <frame name="wlmframe" src="/startwlm/Start_Wlm.htm">
	   <#root>
		<html>
		 <head> 
		  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> 
		  <meta http-equiv="Content-Style-Type" content="text/css"> 
		  <meta http-equiv="Content-Script-Type" content="text/javascript"> 
		  <script language="JavaScript" type="text/javascript">
	var OEMFlag = "0";
	if(OEMFlag == 0 || OEMFlag == 2){
	document.write('<TITLE>Command Center RX</TITLE>');
	document.write('<link rel="shortcut icon" href="../favicon.ico">');
	}else{
	document.write('<TITLE></TITLE>');
	}
	</script>
		  <title>Command Center RX</title>
		  <link rel="shortcut icon" href="../favicon.ico"> 
		  <script language="JavaScript" type="text/javascript" src="../js/jsallWLM.js"></script> 
		  <script language="JavaScript" type="text/javascript" src="../js/LocalNavigationWLM.js"></script> 
		  <script language="JavaScript" type="text/javascript">
	var color_val = "color";
	var logintextboxvalidate = "_Local_login"; //default;
	var CurloginStatus = "1";
	
	[snip]
	
	var iframeBasicSend = '<iframe id="basicsend" name ="basicsend" style="background: transparent" allowtransparency="true" scrolling="no" frameborder="0" onload="resizeFrame(this)"; height:0px;  src='+htmlRef+' >You need an iframes capable browser to view this content.</iframe>';
	parent.iframeBasicSend = iframeBasicSend;

	[snip]
		 </body>
		</html>
	   </#root>
	  </frame> 
	 </frameset> 
	</html>


What do you recommend?

**Comment by hollingsworthd** [comment]
@shackman0 I think that getPageSource should always return the current DOM, not the committed response html. So I'll at least try to fix that for iframes.

**Comment by hollingsworthd** [comment]
I think this may have been fixed from any number of fixes in the last 1.5 months. If this is still an issue, please let me know. I tried on some pages with iframes and it seems ok.

**Comment by shackman0** [comment]
>  I tried on some pages with iframes and it seems ok.

does this mean I no longer need to recurseIntoFrames()?

**Comment by hollingsworthd** [comment]
Glad it works. Yes, I don't think there's a way within the Selenium API where I can recurse and include frame html. It potentially creates invalid xml/html so you'll have to keep using your custom code.

**Comment by shackman0** [comment]
How can I make this code available to others? I’m sure I’m not the only one to have this problem.

Regards,
Floyd Shackelford

“Vision without execution is hallucination.” – Thomas Edison
“… it is the mastery of one model that hinders our adoption of another; our drive for competence that renders us inept” – Greg Satell

[Email signature linkedin.jpg]<http://nl.linkedin.com/pub/floyd-shackelford/54/7a2/59b/>

TOPdesk Headquarters
Martinus Nijhofflaan 2, 2624 ES Delft, The Netherlands
+31 (0)15 270 09 00<tel:+31152700900>
info@topdesk.com<mailto:info@topdesk.com>
www.topdesk.com<http://www.topdesk.com/>

Personal mobile: +31.6.8342.3326

**Comment by hollingsworthd** [comment]
I appreciate it. If you edit [this file](https://github.com/MachinePublishers/jBrowserDriver/blob/master/CLA-corp.txt) to digitally "sign" the contributor's license agreement, I will add an API to JBrowserDriver.java, something like .getCompletePageSource

**Comment by hollingsworthd** [comment]
If you're reading this in email, note I needed to edit my comment above...
