### ISSUE TITLE
doesnt support the  html5(chrome) File System or  Blob Constructors

### ISSUE THREAD

**Issue by typhoid** [MachinePublishers/jBrowserDriver#62]
Can't load webpage that requires html5 file system api and blob constructors. if these features can be activated please explain how thank you

**Comment by hollingsworthd** [comment]
File System API is Chrome only and this is WebKit (not Blink)... support for things like this is closer to Safari than Chrome. It might be possible to implement given that you can make callbacks to Java but it would take some work. From what I've read other browsers don't plan to implement this, so support may never come from merely upgrades of later JREs.

Blob Constructors will probably be supported with Java 9 but I haven't run this on Java 9 yet (it's in beta still).
