### ISSUE TITLE
Cookies do not seem to be respected

### ISSUE THREAD

**Issue by fzakaria** [MachinePublishers/jBrowserDriver#67]
I am setting some cookies for a site however the results are not expected.

The cookies do not seem to be respected whereas if I swap the WebDriver for Firefox they are 
(they are auth cookies so its easy to know if it pass/fails).

I am making sure to also follow best practices outlined [here](http://docs.seleniumhq.org/docs/03_webdriver.jsp#cookies) that dictates visiting a 404 page first to initialize the domain.

**Comment by fzakaria** [comment]
Looks like the fix is to just add (copy) the cookie I received's name & value.
For some reason, other WebDrivers, allow you to resend the whole cookie as long as you do the best practice outlined above.

**Comment by hollingsworthd** [comment]
Can you provide an example cookie with all the attributes? Generally this functionality should work but it's probably failing on domain/path validation. Thanks

**Comment by fzakaria** [comment]
So I would login, then fetch the cookie (so that on subsequent WebDriver instances) I can reload the Cookie and skip authentication.

ChromeDriver & FireFox driver seemed to take the cookie below fine however for JBrowserDriver I had to send only `name` and `value`.
Small discrepancy but just making an issue for any disparity I find while I use the library
(which btw I'm very glad exists).
If its not a big deal or correct to the spec feel free to close.


```json
[  
   "org.openqa.selenium.Cookie",
   {  
      "name":"_auth",
      "value":"XXXXXXXX",
      "path":"/",
      "domain":"vauto.com",
      "expiry":null,
      "secure":false,
      "httpOnly":false
   }
]
```

**Comment by hollingsworthd** [comment]
If I understand right, the only difference between this driver and others and that domain is not required.

I decided not to require the domain, but it will now be set automatically to the domain of the current page. This aligns with how the driver has handled response cookie headers that have no domain set (and real browsers do this too).
