### ISSUE TITLE
Clicking a WebElement

### ISSUE THREAD

**Issue by dbertels** [MachinePublishers/jBrowserDriver#72]
Hi, just a simple question. Say I initialise a driver and get an initial page with 
`driver.get(url_st);`
After I load the page with the driver, can I just use the driver to click on a clickable element to get to another page, like so?
```
driver.getPageSource();
WebElement clickable = driver.findElementById("someId");
if (clickable != null) {
   clickable.click();
   String oddsClickedPage = driver.getPageSource();
}
```
 I tried this, but it seems like the page needs time to load fully. I tried waiting with driver.wait(2000) but that caused a IllegalMonitorStateException.
 
Can you help with this or maybe point me to some examples?

**Comment by hollingsworthd** [comment]
Ideally that should work. Adjusting some settings might improve this.

The ajaxWait settings configures the amount of idle time needed between requests before a page is considered loaded. Defaults to 120 MS but you might need longer. 

There's also a second setting, ajaxResourceTimeout which is the time after which we stop waiting for an ajax request to complete, which defaults to 2000. Each of those are on the Settings.builder()....build() passed to the JBrowserDriver constructor.

If you want to manually sleep, it's probably best to just do Thread.sleep(..). You can do driver.wait(2000) but you'd need to surround it by a synchronized block on driver `synchronized(driver){` however unless you also have code calling `driver.notifyAll()` then it won't be any different than Thread.sleep as nothing in the library is calling notify.

**Comment by dbertels** [comment]
I tried all of the above, but still no cigar. Thanks anyway for the helpful comments.

**Comment by nautilus28** [comment]
I got the same problem, but none of the above works.

**Comment by CamielK** [comment]
Did you try the wait.until method?

`WebDriverWait wait = new WebDriverWait(driver, 10); WebElement elementConfirm = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("delete")));`
        
For example, this waits for the Delete button to be visible, indicating the the page has loaded. You can try different ExpectedConditions to suit your needs

**Comment by hollingsworthd** [comment]
Let me know if this problem still exists in v0.12.0. I think it might be fixed. Also note you can now call `JBrowserDriver.pageWait()` as needed to add manual delays. If it still doesn't work I'd need a test case to reproduce this. Thanks.
