### ISSUE TITLE
NPE in ElementServer

### ISSUE THREAD

**Issue by homaxto** [MachinePublishers/jBrowserDriver#79]
ElementServer.findElementsByXPath() returns null if an exception has been caught. This will result in a NPE in ElementServer.findElementByXPath().

**Comment by hollingsworthd** [comment]
Thanks. I noticed this too and just pushed a fix I had for this, https://github.com/MachinePublishers/jBrowserDriver/commit/3d9240a768006351a53b0efe7969654fe88f795e
