### ISSUE TITLE
ClassCastException while fetching an RSS feed

### ISSUE THREAD

**Issue by sygel** [MachinePublishers/jBrowserDriver#80]
Hello,

I'm getting a classCastException while fetching a RSS feed.
E.g. this site, http://feeds.cfr.org/cfr_main, but other RSS feeds have this problem too.
		
     Settings settings = Settings
		    .builder()
		    .ajaxResourceTimeout(5000)
		    .ajaxWait(5000)
		    .blockAds(true)
		    .headless(true)
		    .ignoreDialogs(true)
		    .requestHeaders(RequestHeaders.CHROME)
		    .ssl("trustanything")
		    .timezone(Timezone.EUROPE_AMSTERDAM)
		    .userAgent(UserAgent.CHROME)
		    .build();
    JBrowserDriver driver = new JBrowserDriver(settings);
    driver.get("http://feeds.cfr.org/cfr_main");
    System.out.println(driver.getStatusCode());
    System.out.println(driver.getPageSource());
    List<WebElement> webElements = driver.findElementsByTagName("item");
    if (webElements != null) 
      System.out.println(webElements.size());
    else
    	System.out.println("webelements was null");
    driver.quit();

[Port 10000] Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List
[Port 10000] 	at com.machinepublishers.jbrowserdriver.ElementServer$17.perform(ElementServer.java:577)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.ElementServer$17.perform(ElementServer.java:573)
[Port 10000] 	at com.machinepublishers.jbrowserdriver.AppThread$Runner.run(AppThread.java:74)
[Port 10000] 	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
[Port 10000] 	at java.security.AccessController.doPrivileged(Native Method)
[Port 10000] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
[Port 10000] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:94)
[Port 10000] 	at com.machinepublishers.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:53)
[Port 10000] 	at java.lang.Thread.run(Thread.java:745)

**Comment by hollingsworthd** [comment]
This was recently fixed, not yet released.
