### ISSUE TITLE
Driver still logs on console even if all *Console properties are set to false

### ISSUE THREAD

**Issue by breadfan** [MachinePublishers/jBrowserDriver#81]
I use JBrowserDriver from scalatest/play and I can't configure it to be silent:
```
case object JBrowserDriverInfo extends BrowserInfo("[JBrowserDriver]", "") {
  override def createWebDriver(): WebDriver = {
    // You can optionally pass a Settings object here,
    // constructed using Settings.Builder
    new JBrowserDriver(
      Settings
        .builder()
        .headless(true)
        .traceConsole(false)
        .wireConsole(false)
        .warnConsole(false)
        .screen(new Dimension(1024, 780))
        .timezone(Timezone.EUROPE_BERLIN)
        .build())
  }
}

```

**Comment by hollingsworthd** [comment]
Must be something with ScalaTest+Play and one of the jBrowserDriver dependencies using log4j or slf4j. I'll look into it.

**Comment by breadfan** [comment]
Thanks, cheers Chris

**Comment by doggie1989** [comment]
+1
I cannot disable the log too...

**Comment by hollingsworthd** [comment]
This is the Logback logger which Scalatest Play uses. I couldn't figure out how to configure it. You can disable it by adding exclusion to your pom and including slf4j-simple instead:

```
<dependency>
  <groupId>org.scalatestplus</groupId>
  <artifactId>play_2.11</artifactId>
  <version>1.4.0</version>
  <exclusions>
    <exclusion>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-simple</artifactId>
  <version>1.7.2</version>
  <optional>true</optional>
</dependency>
```

I've never used ScalaTest (or Scala) so there's probably a better solution but I don't think it's specific to JBrowserDriver.

**Comment by hollingsworthd** [comment]
Also see http://logback.qos.ch/manual/configuration.html

If you put logback-test.xml file with contents `<configuration />` on your classpath it will silence logging. 

Another way to do it is use system property `logback.configurationFile` pointing to the xml config file. Note to get properties to be passed to the forked jBrowserDriver processes, preprend properties with `jbd.rmi.` so use `jbd.rmi.logback.configurationFile` in addition to `logback.configurationFile` (however, this is an unpublished feature and may be removed in future releases).

I don't think there's anything for this project to change to make this nicer, that it's up to ScalaTest Play... but let me know if I'm mistaken.
