### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nycoder67** [MachinePublishers/jBrowserDriver#82]
A shutdown hook is added in the JBrowserDriver constructor and is not removed on close causing a reference to the instance to remain in the ApplicationShutdownHooks.hooks static field. Instances of JBrowserDriver contain a Logs instance where Selenium LogEntry instances accumulate eventually causing OutOfMemoryError depending on the max heap size. JBrowserDriver has no public API allowing the caller to manage the Logs instance.

The condition can be addressed by saving a reference to the shutdown hook created in the constructor and executing+removing it when the JBrowserDriver instance is closed OR using a static inner class for the shutdown hook to separate the JBrowserDriver instance from the hook. In addition, allowing the caller to manage the Logs instance may also be useful.

(Awesome implementation BTW...thanks!)

**Comment by hollingsworthd** [comment]
Excellent, thanks for the info! I'll fix up the shutdown hook.

There is a config setting to limit the log entries, [Settings.builder().maxLogs(int)](http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/Settings.Builder.html#maxLogs-int-) ... the default max may be too big ... they are cleared after a call to [JBrowserDriver.manage().logs().get(null)](http://machinepublishers.github.io/jBrowserDriver/org/openqa/selenium/logging/Logs.html)

Anyhow the leak should be fixed and default settings adjusted to not be causing memory errors.

**Comment by nycoder67** [comment]
Thanks. I implemented a work-around but I'll keep an eye out for the commit/release.
