### ISSUE TITLE
Detecting javascript issues

### ISSUE THREAD

**Issue by cambiph** [MachinePublishers/jBrowserDriver#84]
Is it possible to get any javascript errors that are printed to the console?

**Comment by cambiph** [comment]
Is this an enhancement we can expect soon?
Or do you maybe have a workaround to just get the console output of the driver?

**Comment by hollingsworthd** [comment]
You can execute arbitrary JS with JBrowserDrive.executeScript which maybe you can overrwrite Window Console. There's also headScript in Settings Builder where you can inject any JS into the page before it loads. This isn't a very high priority issue now but I don't think I've had issues open longer than a couple of months.

**Comment by cambiph** [comment]
For some reason the .javascriptLog(boolean boolean) is not available in the Settings class in version 0.11.0

**Comment by hollingsworthd** [comment]
I made that commit after the 0.11.0 release. Just now I uploaded 0.11.1-SNAPSHOT to Maven Central Repo... try explicitly setting that as the version in your pom.

Note the API may change. Given it's only a snapshot release it would be easy for me to take into account feedback you have. `JBrowserDriver.manage().logs().get("javascript")`

**Comment by cambiph** [comment]
Ok, thank you for the feedback.
I thought I was going crazy because I couldn't find it.
I'll change the version and provide you with feedback.

On Wed, Apr 13, 2016 at 11:46 AM, D. Hollingsworth <notifications@github.com

**Comment by cambiph** [comment]
If I read your code right, all I have to do is set javascriptLog to true in the Settings builder and then using driver.manage().logs().get("javascript"), correct?

However I don't see the log messages.
Consider this code:

`        driver = new JBrowserDriver(getSettings());
        driver.get("http://the-internet.herokuapp.com/javascript_error");
        for(LogEntry entry : driver.manage().logs().get("javascript").filter(Level.ALL)) {
            logger.debug(entry.getMessage());
        }
        driver.quit();`

`...
return Settings.builder()
                .ajaxResourceTimeout(30000)
                .ajaxWait(30000)
                .blockAds(true)
                .javascript(true)
                .ignoreDialogs(true)
                .proxy(proxy)
                .traceConsole(false)
                .javascriptLog(true)
                .quickRender(true)
                .build();`

Using 0.11.1-SNAPSHOT

**Comment by hollingsworthd** [comment]
I get `[Port 10000] [2016-04-14T11:31:32-0400] [FINER] {"window_onerror":"TypeError: 'undefined' is not an object (evaluating 'document.propertyThatDoesNotExist.xyz')","filename":"http://the-internet.herokuapp.com/javascript_error","lineno":7}`

Maybe delete 0.11.1-SNAPSHOT from your local maven m2 cache. I added the window onerror hook after you may have updated

**Comment by cambiph** [comment]
I got it to work now.
The only weird thing is that driver.manage().logs().get("javascript") returns a List of logentries.
However, if you filter on Level.ALL, none are returned.
I bypassed this by using the getAll() function and using a for-loop:

`        List<LogEntry> logEntryList = driver.manage().logs().get("javascript").getAll();
        for(int i = 0; i < logEntryList.size(); i++) {
            logger.info(logEntryList.get(i).getMessage());
        }`
