### ISSUE TITLE
custom data attributes

### ISSUE THREAD

**Issue by navels** [MachinePublishers/jBrowserDriver#85]
Is there not support for custom data attributes?  I've got an element with one:
    &lt;div data-selected="foo">&lt;/div>
but `getAttribute("data-selected")` on this element returns the empty string instead of "foo".

Also, if the attribute isn't on the element, I get the empty string instead of null.  The spec stipulates a null value is returned if the attribute does not exist.

**Comment by hollingsworthd** [comment]
Thanks for letting me know. I'll look into it. I think it should work, so probably a bug.
