### ISSUE TITLE
Nothing is rendered - OS X + Clojure.

### ISSUE THREAD

**Issue by shriphani** [MachinePublishers/jBrowserDriver#91]
Hi,

Thanks for this project - lots of little upgrades to selenium I like a lot.

I have tried to use this library from clojure on OS X  but I always get blank pages with no text on them.

Here's a simple function: https://github.com/shriphani/test-render/blob/master/src/test_render/core.clj

That function goes to http://blog.shriphani.com and takes a screenshot.

I essentially get a blank page as the output:

https://raw.githubusercontent.com/shriphani/test-render/master/screenshot.png

This might be source of the problem. `lein` (the clojure build tool) doesn't like the maven coords you have provided so I had to use this: `[com.machinepublishers/jbrowserdriver "0.11.0"]`

Any ideas?

**Comment by shriphani** [comment]
Hi, I tried the same example in java: https://github.com/shriphani/RenderTest/blob/master/src/main/java/Main.java

It picks up the source just fine but the screenshot is blank: https://github.com/shriphani/RenderTest/blob/master/screenshot.png

**Comment by hollingsworthd** [comment]
I think that fixes it. Let me know if problems persist. Now in 0.11.1-SNAPSHOT. Will be in next release.

**Comment by shriphani** [comment]
@hollingsworthd I changed my `pom.xml` to use 0.11.1-SNAPSHOT . I don't think you have pushed to maven yet. Can you?

**Comment by shriphani** [comment]
Ok installed the current version using mvn clean compile install.

The screenshot is still incomplete:

https://github.com/shriphani/RenderTest/blob/master/screenshot.png

And the fonts look nothing like the version in the browser - are webfonts etc ignored?

Best,
Shriphani

**Comment by hollingsworthd** [comment]
Try setting [ajaxWait](http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/Settings.Builder.html#ajaxWait-long-) to something higher than 150 and [quickRender](http://machinepublishers.github.io/jBrowserDriver/com/machinepublishers/jbrowserdriver/Settings.Builder.html#quickRender-boolean-) to false (yes, fonts and images ignored by default).

**Comment by shriphani** [comment]
Woo!

https://github.com/shriphani/RenderTest/blob/master/screenshot.png

**Comment by hollingsworthd** [comment]
Good to hear. Out of curiosity, what did you set ajaxWait to?

**Comment by shriphani** [comment]
200

**Comment by shriphani** [comment]
https://github.com/shriphani/RenderTest/blob/master/src/main/java/Main.java
