### ISSUE TITLE
Client certs

### ISSUE THREAD

**Issue by smcnamara3** [MachinePublishers/jBrowserDriver#93]
I need to test a website that requires a client cert to be submitted over SSL/TLS for authentication. This isn't easy for _any_ existing automated test solutions, but currently it seems impossible with jBrowserDriver without editing the source code...?

All the options for ignoring _server_ certificates are useless, because the server literally will not let the client connect at all unless they provide the correct certificate. It's part of the authentication layer of a locked-down app.

**Comment by hollingsworthd** [comment]
I think this will work currently but I've never tried it. The SSL context used is Java's default (if you don't touch any of the Settings builder SSL-related options). Java calls the client certs the 'keystore' and the server certs the 'truststore'. So I think importing your client cert into the keystore will do the trick: http://quakology.blogspot.com/2009/06/how-to-use-ssl-with-client-certificate.html

**Comment by smcnamara3** [comment]
Oh, so you're saying that this is somehow a WebKit implementation that's so hooked into Java that it actually uses Java's SSL sockets layer!?

...

That's *amazing*.

If this turns out to be true, this issue is solved; I'm very familiar with Java's SSL stuff.

Thank you!

**Comment by hollingsworthd** [comment]
Yes, it's very much hooked into Java. And for the networking code, I went further and hooked it into Apache HttpComponents. WebKit exists here to do CSS layout and JS execution. Most everything else happens in the JRE.

**Comment by hollingsworthd** [comment]
If it doesn't work let me know. It will be a matter of enhancing https://github.com/MachinePublishers/jBrowserDriver/blob/master/src/com/machinepublishers/jbrowserdriver/StreamConnectionClient.java
